collector/connector/validationconnector/README.md, collector/processor/obfuscationprocessor/config.go, collector/processor/obfuscationprocessor/factory.go, pkg/otel/assert/README.md, tools/trace_verify/main.go
Hypothesis: Creating this PR will result in EasyCLA running which will allow me to push -f the branch.
(This from #1, where the same happened.)
=> Minor fixes from  (#212)

collector/examples/bridge/edge-collector.yaml, collector/examples/loopback/config.yaml, collector/examples/metadata-bridge/edge-collector.yaml, collector/examples/metadata-bridge/saas-collector.yaml, collector/examples/recorder/README.md, collector/examples/recorder/replay.yaml, collector/examples/recorder/target.yaml, collector/examples/synthesize/replay.yaml, collector/gen/exporter/otlpexporter/factory.go, collector/gen/receiver/otlpreceiver/factory.go
This is the fourth step documented in https://github.com/open-telemetry/otel-arrow/issues/3.
While revising the example yamls for this change, also corrected a historical error. The OTel standard gRPC port is 4317, not 4318 -- correct this error.
=> Update component names to "otelarrow"

collector/exporter/otelarrowexporter/internal/arrow/exporter.go, collector/exporter/otelarrowexporter/internal/arrow/exporter_test.go, collector/exporter/otelarrowexporter/internal/arrow/stream.go, collector/exporter/otelarrowexporter/internal/arrow/stream_test.go
As discussed in https://github.com/grpc/grpc-go/issues/6504, the client should add jitter when configuring `max_connection_age_grace` because we expect each stream will create a new connection. Since connection storms will not be spread automatically by gRPC in this case, apply client jitter.
Part of #6.
=> Subtract 0-5% of max_stream_lifetime, when set; support unlimited max_stream_lifetime

CODEOWNERS
@moh-osman3 is already in https://github.com/orgs/open-telemetry/teams/arrow-approvers/members
adding to CODEOWNERS makes his approval actually count in presubmit checks.
=> Add moh-osman3 as approver to CODEOWNERS

collector/cmd/otelarrowcol/build.yaml, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/go.mod, versions.yaml
Includes #13, #20, #21, #22, #23.
Releasing often - this makes it easier to integrate for `go.mod` users.
=> Prepare release v0.2

collector/exporter/otelarrowexporter/config_test.go, collector/exporter/otelarrowexporter/factory.go, collector/exporter/otelarrowexporter/testdata/config.yaml, collector/exporter/otelarrowexporter/testdata/default.yaml
Here at Lightstep we think that round_robin is a reasonably good default load balancer for OTel Arrow, while `pick_first` is what we get without setting something in this field. `pick_first` is not a reasonably good default load balancer for OTel Arrow. This change was documented in #29 already.
Fixes #32.
=> Set the default balancer name to round_robin

collector/cmd/otelarrowcol/build.yaml, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/exporter/otelarrowexporter/dead.code, collector/go.mod, versions.yaml
Release v0.3.0 includes:
- https://github.com/open-telemetry/otel-arrow/pull/24
- #29 
- #30 
- #36 
This release includes a BREAKING CHANGE 🛑 🛑 🛑 🛑 🛑.
We do not anticipate another of these, it merely renames/enumbers status codes to match the gRPC status code numbering scheme. However, since status code 0 stays the same, it will result in unusual looking errors but should be safe to deploy the receivers first. Their CANCELED (i.e., SERVER_SHUTDOWN) will read as UNAVAILABLE, etc.
See #27.
=> Release 0.3.0

pkg/config/config.go
Prior to this PR, by default, dictionaries could hold up to 2^32-1 entries, which can be quite large in terms of memory usage depending on the telemetry workload handled by the OTel Arrow Encoder.
This PR changes this limit from default to 2^16-1 to keep overall memory usage low.
A more sophisticated strategy could be based on calculating the entropy for each column to determine earlier when it is worth using or not a dictionary encoding for each column.
=> Change default limit dictionary index size to 2^16

collector/processor/obfuscationprocessor/processor.go, collector/processor/obfuscationprocessor/processor_test.go
While working with the obfuscation processor to transfer some internal data, I noticed some strings we were not ciphering.
=> obfuscation processor: cipher the event name

collector/cmd/otelarrowcol/build.yaml, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/go.mod, versions.yaml
Since we still do not have a changelog automation, this is what is included since v0.3.0 worthy of note:
#47
#52
#53 
#54 
#55 
#56
#57 
README improvements,
Obfuscation processor fixes.
=> Release v0.5.0

collector/receiver/otelarrowreceiver/internal/arrow/arrow.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow_test.go, collector/receiver/otelarrowreceiver/internal/logs/otlp.go, collector/receiver/otelarrowreceiver/internal/logs/otlp_test.go, collector/receiver/otelarrowreceiver/internal/metrics/otlp.go, collector/receiver/otelarrowreceiver/internal/metrics/otlp_test.go, collector/receiver/otelarrowreceiver/internal/trace/otlp.go, collector/receiver/otelarrowreceiver/internal/trace/otlp_test.go, collector/receiver/otelarrowreceiver/otlp.go
This PR removes the use of the deprecated `obsreport.Receiver` after a recent collector upgrade to v0.87.0. See https://github.com/open-telemetry/otel-arrow/pull/61#pullrequestreview-1676982754
=> (otelarrowreceiver): remove deprecated functions after v0.87.0 collector upgrade

collector/cmd/otelarrowcol/build.yaml, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/go.mod, versions.yaml
This includes a minor [memory optimization](https://github.com/open-telemetry/otel-arrow/pull/65) and updates collector dependencies to v0.87.0
=> Release v0.6.0

collector/receiver/otelarrowreceiver/config.go, collector/receiver/otelarrowreceiver/config_test.go, collector/receiver/otelarrowreceiver/factory.go, collector/receiver/otelarrowreceiver/otlp.go, collector/receiver/otelarrowreceiver/testdata/bothmemlimit.yaml, collector/receiver/otelarrowreceiver/testdata/config.yaml, collector/receiver/otelarrowreceiver/testdata/oldmemlimit.yaml
While adding compression settings, I noticed the receiver Arrow.MemoryLimit is a non-standard configuration for large sizes, which are generally configured with a `_mib` suffix for MiB. Before introducing more consistency issues, I've fixed it w/ compatibility support. When the old value is configured it will be rounded up to the next MiB and used instead of the new field.
Part of #35.
=> Replace memory_limit with memory_limit_mib

.github/workflows/ci.yml, CHANGELOG.md, Makefile, collector/cmd/otelarrowcol/go.mod, collector/connector/validationconnector/go.mod, collector/exporter/otelarrowexporter/go.mod, collector/otelarrowcol-build.yaml, collector/receiver/otelarrowreceiver/go.mod, versions.yaml
As with #91, this release is going to face problems with passing tests during while its new version tags are unreleased.
We will bypass the automatic checks with this release, and if the results are acceptable we will address this in the future with an updated release procedure.
We cannot run `go work sync` with unreleased version tags.
=> Release 0.7.0

collector/cmd/otelarrowcol/main.go, collector/connector/validationconnector/go.sum, collector/exporter/fileexporter/go.sum, collector/exporter/otelarrowexporter/go.sum, collector/otelarrowcol-build.yaml, collector/receiver/otelarrowreceiver/go.sum
Not sure how, but the `sed` operation to update version numbers missed a file in the v0.8 release, so the `sed` pattern didn't match in the v0.9 release.
=> Update main version, was somehow missed in the v0.9 release

collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/go.sum, collector/examples/generator/hipster_shop.yaml, collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go, collector/processor/concurrentbatchprocessor/config.go, collector/processor/concurrentbatchprocessor/config_test.go, collector/processor/concurrentbatchprocessor/factory.go, collector/processor/concurrentbatchprocessor/testdata/config.yaml
This PR adds a new config option in the `concurrentbatchprocessor` named `max_in_flight_bytes`. This config option will be used by processor to control admission (using a semaphore) into the producer queue based on the size of requests.
Fixes #80.
Fixes #11.
=> (concurrentbatchprocessor): add in-flight byte limit to producer queue

collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go, collector/processor/concurrentbatchprocessor/metrics.go
Fixes #110 (with #111).
This adds an up-down counter of bytes acquired and released, since the semaphore does not expose the same quantity.
Also, this moves the semaphore into the batch processor, instead of in the shard. The limit therefore applies to all shards at once, which I think is what we intend, or at least it's the simpler option to reason about vs allowing each shard to have an independent limit.
=> Add in-flight-bytes metric to concurrent batch processor

pkg/otel/arrow_record/consumer.go
This field has caused a (predictable) cardinality explosion in our internal pipeline monitoring setup. This leaves the feature in but disabled at Detailed level. While the collectorconfig package won't parse a value greater than Detailed, callers can still pass `Detailed+1` to enable.
=> Disable the stream_unique metric attribute at Detailed level

collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go, collector/processor/concurrentbatchprocessor/go.mod
This PR checks all incoming contexts for a given batch. If all contexts are the same, the parent context is no longer broken and is passed directly into `export`. Otherwise, the parent context must be broken and links to the incoming contexts are attached to the new span context.
This will help our efforts in debugging metrics SDKs because no longer breaking the parent span means we can see the latency of `concurrentbatchprocessor`
=> (concurrentbatchprocessor): avoid breaking parent span if used in SDK export pipeline

CHANGELOG.md, collector/processor/concurrentbatchprocessor/config.go, collector/processor/concurrentbatchprocessor/config_test.go, collector/receiver/otelarrowreceiver/config.go, collector/receiver/otelarrowreceiver/config_test.go, collector/receiver/otelarrowreceiver/testdata/bothmemlimit.yaml, collector/receiver/otelarrowreceiver/testdata/oldmemlimit.yaml
Simply remove two deprecated fields. The v0.13 release includes support for the old and new fields to support migration.
=> Remove two deprecated fields [chore]

CHANGELOG.md, collector/exporter/otelarrowexporter/otlp.go, collector/exporter/otelarrowexporter/otlp_test.go
Described and tracked in https://github.com/open-telemetry/opentelemetry-collector/issues/9243.
The otelarrow export component copied this code from the core OTLP exporter, so it has the same bug.
=> Return success on PartialSuccess

.github/workflows/ci.yml
Following the release process for v0.14.0.
=> Post v0.14.0: re-enable CI/CD

collector/exporter/otelarrowexporter/internal/arrow/stream.go, collector/netstats/handler.go, collector/netstats/netstats.go, collector/netstats/netstats_test.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow.go
This PR adds a new method to the netstats reporter, called `SetSpanAttributes`. This method adds uncompressed request size as an attribute to the provided span and explicitly sets the span status in the case of an error. This method is used to track errors for both `server.Send` and `client.Send`  grpc  operations.
=> add uncompressed bytes to receiver and exporter span attributes

collector/receiver/otelarrowreceiver/internal/arrow/arrow.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow_test.go, collector/receiver/otelarrowreceiver/otelarrow.go
Resolves https://github.com/open-telemetry/otel-arrow/issues/148
This PR adds two metrics to track the number of items and bytes that are pending in the receiver. Specifically when used with the `concurrentbatchprocessor` requests can be have a long lifetime in receiver due to the in flight byte limiter in the `concurrentbatchprocessor`.
=> (otelarrowreceiver): add updown counters to track number of bytes and items pending

collector/go.mod, collector/go.sum, collector/testutil/testutil.go
This PR unblocks https://github.com/open-telemetry/opentelemetry-collector/pull/9546
=> [chore] remove method using a deprecated struct

collector/receiver/otelarrowreceiver/otelarrow_test.go
Remove a deprecated package that is removed completely from collector `v0.97.0` (https://github.com/open-telemetry/opentelemetry-collector/pull/9724). This seems to be blocking a collector upgrade.
Attempt to upgrade collector to v0.97.0 results in 
```
go: found github.com/open-telemetry/otel-arrow/collector/receiver/filereceiver in github.com/open-telemetry/otel-arrow/collector/receiver/filereceiver v0.18.0
go: found github.com/open-telemetry/otel-arrow/collector/receiver/otelarrowreceiver in github.com/open-telemetry/otel-arrow/collector/receiver/otelarrowreceiver v0.18.0
go: finding module for package go.opentelemetry.io/collector/obsreport/obsreporttest
go: github.com/open-telemetry/otel-arrow/collector/cmd/otelarrowcol imports …
```
=> (otelarrowreceiver): remove obsreporttest package

.github/workflows/ci.yml
This was disabled to release otel-arrow v0.20.0. Should be reenabled now that the release is out.
=> Enable ci/cd build and test

CHANGELOG.md, collector/admission/README.md, collector/admission/boundedqueue.go, collector/admission/boundedqueue_test.go, collector/go.mod, collector/go.sum
This PR adds a new semaphore object to limit both on bytes and number of waiters. This should help with some memory issues in the collector where the receiver holds on to too much memory, either due to large/frequent requests or too many waiters blocked. Related to https://github.com/open-telemetry/otel-arrow/issues/173
=> (boundedqueue): new semaphore implementation

collector/exporter/otelarrowexporter/internal/arrow/bestofn.go, collector/exporter/otelarrowexporter/internal/arrow/exporter.go, collector/exporter/otelarrowexporter/internal/arrow/exporter_test.go, collector/exporter/otelarrowexporter/internal/arrow/prioritizer.go, collector/exporter/otelarrowexporter/internal/arrow/stream.go, collector/exporter/otelarrowexporter/internal/arrow/stream_test.go, collector/receiver/otelarrowreceiver/config_test.go, collector/receiver/otelarrowreceiver/factory.go
Minor lint fixes needed to keep the two code-bases in sync.
- Remove unused context argument from nextWriter()
- Do not name a field `N`
- Fix unused variable `rnd`
- Harden the stream-lifetime test w/ use of context
- Etc.
=> Lint fixes from open collector-contrib PRs.

.github/workflows/ci.yml
This was disabled to release otel-arrow v0.23.0. Should be reenabled now that the release is out.
=> Re-enable ci/cd

collector/exporter/otelarrowexporter/internal/arrow/common_test.go, collector/exporter/otelarrowexporter/internal/arrow/exporter_test.go, collector/exporter/otelarrowexporter/internal/arrow/stream.go
This addresses the test flake occasionally seen in this repository. There was a channel being set to `nil` inappropriately, and uses of a direct call to channel close() when the more appropriate pattern is to cancel a context. This fixes the test flakes and lint problems from the upstream repository in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31996.
=> Backport test & lint fixes from opentelemetry-collector-contrib/31996

collector/receiver/otelarrowreceiver/README.md, collector/receiver/otelarrowreceiver/config.go, collector/receiver/otelarrowreceiver/config_test.go, collector/receiver/otelarrowreceiver/factory.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow_test.go, collector/receiver/otelarrowreceiver/testdata/config.yaml
This PR adds information about the new config options added in https://github.com/open-telemetry/otel-arrow/pull/181 to the otelarrowreceiver readme.
=> (otelarrowreceiver): document new config options

collector/receiver/filereceiver/file_reader.go, collector/receiver/filereceiver/file_reader_test.go, collector/receiver/filereceiver/receiver.go
This makes it clear when a test has completed, which will be helpful in diagnosing successful replay of file data using this component.
=> Print a notice when the file receiver reaches EOF

collector/exporter/otelarrowexporter/config.go, collector/exporter/otelarrowexporter/config_test.go, collector/exporter/otelarrowexporter/factory.go, collector/exporter/otelarrowexporter/factory_test.go, collector/exporter/otelarrowexporter/internal/metadata/generated_status.go, collector/exporter/otelarrowexporter/otelarrow_test.go
Automated content generation:
Copy diffs from the collector-contrib repository back into this repo's otelarrowexporter, avoiding divergence.
From https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/726ffec310654866f7c3a1b668eec288e36c09e5.
=> Backport exporter changes from collector-contrib

collector/exporter/otelarrowexporter/otelarrow_test.go
There is a test flake, seen here. I believe this is for failing to shutdown the service, which causes a 100s long run-time. This does not explain a deadlock, but we aren't sure that has happened, vs a timeout due to CPU shortage.
https://github.com/open-telemetry/otel-arrow/actions/runs/9180018006/job/25243494523
=> [otelarrowexporter] Deflake TestSendArrowTracesNotSupported

CHANGELOG.md, collector/exporter/otelarrowexporter/internal/arrow/stream.go, collector/netstats/handler.go, collector/netstats/netstats.go, collector/netstats/netstats_test.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow.go
This is a simplification.
We can instrument the same information with fewer API calls, and I had encountered this as a readability problem in the exporter / receiver.  Since CountSend and CountReceive already see the four parameters correctly, and since the Span already has a name indicative of whether it is exporter or receiver, we can report the span attributes from inside the Count methods using fixed attribute names.
The exporter and receiver code avoids use of MetricsLevel to gate calls into the netstats code, so that span instrumentation is independent of metrics detail. Netstats is level-aware, so this is not a change in observability.
To avoid complicating release cycles with collector-contrib, I've left behind a no-op interface which can be removed after several release cycles.
=> [collector/netstats] Move span API calls into Count methods

pkg/otel/arrow_record/consumer.go, pkg/otel/common/arrow/allocator.go, pkg/otel/common/arrow/allocator_test.go
Part of #210.
This updates memory-limit error handling because, prior to this fix, there were two fallbacks.
(1) the use of os.Stderr to print the message that we had lost
(2) a test for the expected number of records to match
The first is now removed (i.e. no printing to os.Stderr). The second is now an internal error.
The consumer is expected to test for the memory limit error explicitly (e.g., and handle it as ResourceExhausted). A new function is added to do this (NewLimitErrorFromError) that parses the message using a regexp. An upstream issue report and PR will be filed with Arrow-Go to overcome this in the future.
See https://github.com/apache/arrow/pull/41989.
=> Call IPCReader.Err() after reader loop

collector/receiver/otelarrowreceiver/internal/arrow/arrow.go
Part of https://github.com/open-telemetry/otel-arrow/pull/210.
Mainly, fixes a race in the use of `inFlightWG` which is meant to be per-stream but is per-Receiver presently.
Secondly, re-order and rename of the fields passed to the "arrow stream error" log statement, so that it matches the Exporter. This is used as the basis of a test for logging consistency and there was otherwise an unintentional disagreement ("which" and "where").
=> Fix inFlightWG race in the OTel-Arrow receiver

collector/exporter/otelarrowexporter/internal/arrow/exporter.go, collector/exporter/otelarrowexporter/internal/arrow/exporter_test.go
This is consistent with gRPC behavior for unary exporters, as with for HTTP exporters.
It also helps us test with realistic conditions in the new integration test of #210.
https://grpc.io/docs/guides/deadlines/ explains why the default behavior is the way it is for unary gRPC. This is also the case for Golang's net/http client, which is used for the OTLP/HTTP exporter. Therefore, it seems the right thing to do for Arrow as well. Further, if we were to support extending the deadline on purpose, it would belong in the exporterhelper code (IMO).
=> Avoid work for already-canceled requests

CHANGELOG.md
These changes would've made merge conflicts 5 times, so I've updated the CHANGELOG in a new PR.
=> Update changelog w/ 5 recent PRs

collector/exporter/otelarrowexporter/internal/arrow/stream.go, collector/exporter/otelarrowexporter/internal/arrow/stream_test.go, collector/receiver/otelarrowreceiver/internal/arrow/arrow.go
Fix missing maxStreamLifetime by checking `stream.workState.maxStreamLifetime` instead of `stream.maxStreamLifetime`, because `stream.maxStreamLifetime` is never set anywhere.
This PR also fixes missing `otel_arrow_stream_recv` parent spans in recently observed traces.
=> Fix missing maxStreamLifetime timeout

CHANGELOG.md, collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go
A missing `func (_) Unwrap() error` makes the receiver not able to unwrap the exporter errors. 
Fixes #234.
=> Wrap the error used in concurrentbatchprocessor

collector/processor/concurrentbatchprocessor/batch_processor.go
If there's a custom TracerProvider set in config, use that. Otherwise, fall back to the global otel provider.
=> collector/batch processor: honor TracerProvider from cfg

collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go
Three minor changes in CBP instrumentation:
- unconditionally create a span, even in cases where there is a single parent; less confusing to always have a span w/ observable latency, otherwise users have to look at each receiver individually.
- end the span after the export call, vs immediately
- link in both directions, allows the incoming requests to link to their outgoing batch easily w/o depending on trace backend features.
I also ran into some test debts, fixed to cover the new behavior.
=> [concurrentbatchprocessor] Consistent span creation, latency, bi-directional links

collector/processor/concurrentbatchprocessor/README.md, collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/config.go, collector/processor/concurrentbatchprocessor/config_test.go
For OTel-Arrow, we now prefer to limit admitted bytes in the receiver.  Allow the function to be disabled in the CBP.
([Refer to this for reciever admission control](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/otelarrowreceiver/README.md#arrow-specific-configuration).)
=> [concurrentbatchprocessor] Allow max_in_flight_size_mib to be set to zero to disable inflight limit

collector/admission/boundedqueue.go
Alternative to https://github.com/open-telemetry/otel-arrow/pull/242
Allow us to monitor when requests are being blocked by admission limits.
=> Record admission-blocked event as a span & duration

CHANGELOG.md, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/connector/validationconnector/go.mod, collector/otelarrowcol-build.yaml, versions.yaml
- Concurrent batch processor: tracing improvements. [#238](https://github.com/open-telemetry/otel-arrow/pull/238), [#241](https://github.com/open-telemetry/otel-arrow/pull/241)
- Update to latest OTel-Collector & OTel-Go dependencies.  Remove collector packages now included in collector-contrib/internal/otelarrow. [#245](https://github.com/open-telemetry/otel-arrow/pull/245)
- Concurrent batch processor: remove support for in-flight limits. [#247](https://github.com/open-telemetry/otel-arrow/pull/248)
=> Release v0.26.0

CHANGELOG.md, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, versions.yaml
- Concurrent batch processor: concurrency limit for legacy behavior or otherwise. [#254](https://github.com/open-telemetry/otel-arrow/pull/254)
- Concurrent batch processor: EarlyReturn legacy compat feature. [#253](https://github.com/open-telemetry/otel-arrow/pull/253)
- Concurrent batch processor: Synchronize with upstream; removes in-flight bytes metric, 
removes panic recovery as unnecessary divergence. [#251](https://github.com/open-telemetry/otel-arrow/pull/251)
- Update collector dependencies to v0.110.0/v1.16.0; remove validation connector [#252](https://github.com/open-telemetry/otel-arrow/pull/252)
=> Release v0.27.0

README.md
As the [issue](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26491) tracking moving exporter/receiver components from `otel-arrow` to `open-telemetry/opentelemetry-collector-contrib` has been marked as completed, we can update the "Project deliverables" in readme doc.
This PR also fixes some dead links.
=> fix(readme): Update README with new collector component links

collector/processor/concurrentbatchprocessor/batch_processor.go, collector/processor/concurrentbatchprocessor/batch_processor_test.go
This tests and fixes a deadlock in the concurrent batch processor, one that was especially easy to see with EarlyReturn=true, however exists either way. The bug was introduced in https://github.com/open-telemetry/otel-arrow/pull/251 when it removed a `defer func()` from `consumeAndWait()` by mistake.
This is now covered by testing. This is fixed w/o a `defer func() { ... }`. The older code was both counting responses and updating a semaphore. Now that we only count responses and do not update a semaphore, there is no need to defer. The batcher will avoid sending to the waiter when the waiter's context is canceled.
=> (concurrentbatchprocessor): Fix deadlock, test EarlyReturn feature

collector/processor/concurrentbatchprocessor/batch_processor.go
This avoids a pitfall in which we repeatedly re-slice `b.pending` to `b.pending[1:]`, which causes the slice to be re-allocated instead of re-used. To re-use the slice, shift its contents by one, zero the final element, and shorten it by one.
=> (concurrentbatchprocessor): Allow re-use of the pending slice

collector/cmd/otelarrowcol/components.go, collector/cmd/otelarrowcol/main_windows.go, pkg/otel/metrics/arrow/ehistogram_dp.go, pkg/otel/metrics/arrow/histogram_dp.go, pkg/otel/metrics/arrow/number_data_point.go
Update the nullable settings of fields that are actually nullable in arrow schema.
- Fix #263
=> fix: respect nullable settings in arrow schema

pkg/datagen/metrics.go
See https://github.com/open-telemetry/otel-arrow/issues/261 for a description of the issue
=> Fix bucket count in FakeGen Histogram

CHANGELOG.md, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, versions.yaml
- Fix nullable setting in Arrow schema. [#264](https://github.com/open-telemetry/otel-arrow/pull/264)
- Fix bucket count used in test histogram data. [#265](https://github.com/open-telemetry/otel-arrow/pull/265)
- Update to v0.111.0 collector dependencies; concurrent batch processor component name fix. [#266](https://github.com/open-telemetry/otel-arrow/pull/266)
=> Release v0.29.0

collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, versions.yaml
- Update to v0.114.0 collector dependencies. [#274](https://github.com/open-telemetry/otel-arrow/pull/274)
- Empty SpanID bug-fix. [#273](https://github.com/open-telemetry/otel-arrow/pull/273)
=> Release v0.31.0

pkg/arrow/from_record.go, pkg/otel/common/otlp/attributes.go, pkg/otel/common/otlp/resource.go, pkg/otel/common/otlp/scope.go, pkg/otel/logs/otlp/related_data.go, pkg/otel/metrics/otlp/ehistogram.go, pkg/otel/metrics/otlp/exemplar.go, pkg/otel/metrics/otlp/histogram.go, pkg/otel/metrics/otlp/number_data_point.go, pkg/otel/metrics/otlp/related_data.go, pkg/otel/metrics/otlp/summary.go, pkg/otel/traces/otlp/event.go, pkg/otel/traces/otlp/link.go, pkg/otel/traces/otlp/related_data.go
Rather than creating many implementations of the AttributesStore per type, let's use the new Go generic types.
Starting to use this code as a library I was wondering if this was possible. Turns out it is.
=> pkg: Create generic AttributesStore

CHANGELOG.md, collector/cmd/otelarrowcol/components.go, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, versions.yaml
- Make a generic `AttributesStore` in pkg/arrow. [#276](https://github.com/open-telemetry/otel-arrow/pull/276)
- Update to v0.117.0 collector dependencies. [#277](https://github.com/open-telemetry/otel-arrow/pull/277), [#279](https://github.com/open-telemetry/otel-arrow/pull/279)
- Deprecate local versions of `fileexporter` and `filereceiver` in favor of upstream components with related README changes. [#278](https://github.com/open-telemetry/otel-arrow/pull/278)
- Made an incremental step towards deprecating `MetricsLevel` usage in the project. [#283](https://github.com/open-telemetry/otel-arrow/pull/283)
=> Release v0.32.0

CHANGELOG.md, collector/cmd/otelarrowcol/components.go, collector/cmd/otelarrowcol/go.mod, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, versions.yaml
- Upgrade to v0.119.0 of collector dependencies. [#285](https://github.com/open-telemetry/otel-arrow/pull/285), [#286](https://github.com/open-telemetry/otel-arrow/pull/286)
- Perform additional updates in otel-arrow for upstream `MetricsLevel` deprecation. [#287](https://github.com/open-telemetry/otel-arrow/pull/287)
=> Release v0.33.0

README.md
Add several badges to the main README:
* Slack channel
* Build status (main branch)
* OpenSSF
Related to #289.
=> Add slack/build/openssf badges to the main README

.github/workflows/go-ci.yml, README.md
There were a few undiscovered issued in #302 
1. Status badge in README.md became outdated
1. Go-CI action which uses `codeql` became unable to write, likely due to missing [security-events: write permission](https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions)
1. Rust-CI Clippy step fails build on `/main` branch with warnings even though it passes in CI build
This PR addresses (1) and (2), still trying to find a solution for (3)
=> GitHub Actions fixes after Go+Rust refactor

rust/otel-arrow-rust/Cargo.lock, rust/otel-arrow-rust/Cargo.toml, rust/otel-arrow-rust/src/otlp/data_points/exp_histogram.rs, rust/otel-arrow-rust/src/otlp/data_points/histogram.rs, rust/otel-arrow-rust/src/otlp/data_points/number.rs, rust/otel-arrow-rust/src/otlp/data_points/summary.rs, rust/otel-arrow-rust/src/otlp/metric.rs
This PR fixes some errors found in telegen tests:
- `name` and `start_time_unix_nano` should be optional
- `schema_url` and `description` should be `DictionaryArray`s
A dependency on arrow-ipc is added to handle `DictionaryArray`.
=> fix: errors in telegen tests

.github/workflows/go-ci.yml, .github/workflows/rust-ci.yml
Since #317 forecasts ongoing Rust-CI failures for the foreseeable future, it is convenient to only run Rust CI when the git diff actually touches something under the `rust/` directory (and vice-versa for the Go CI).
This will be a little cleaner in the future if all Go code is isolated under a `go/` directory. For now, the Go-CI will run if something outside of `rust/` is touched.
Will also help in cases like #311 which only touch Go code - hiding unrelated job failures.
=> Isolate Go and Rust CIs by file path

.github/workflows/go-ci.yml, .github/workflows/rust-ci.yml
See https://github.com/EmbarkStudios/cargo-deny-action?tab=readme-ov-file#recommended-pipeline-if-using-advisories-to-avoid-sudden-breakages
Took inspiration from the above to restructure cargo deny invocation. Desired state:
- Only 1 cargo_deny job for each `/rust` subfolder
- Isolated cargo_deny steps inside that job that always run independently of others
In this way, we aviud exponentially increasing the number of running jobs but ALSO can see isolated error messages for each portion of the cargo deny workflow (advisories vs licenses vs ...)
=> Improve cargo deny invocation for isolated logging

rust/beaubourg/deny.toml, rust/otel-arrow-rust/deny.toml
Per #313, allowing certain licenses in cargo_deny execution
=> Temporarily allow Unicode and CC0 licenses where applicable

.github/workflows/go-ci.yml, .github/workflows/rust-audit.yml, .github/workflows/rust-ci.yml
Per [Security Overview - Code Scanning Alerts](https://github.com/open-telemetry/otel-arrow/security/code-scanning) it is best practice to pin workflow action dependencies to specific commit hashes to avoid any unexpected and/or malicious behavior changes.
These findings were recently surfaced by merge of #314, enabling ossf-scorecard scanning, which is happening across all OTel repositories.
Should also help improve OSSF scorecard, see #289.
=> Pin workflow actions to commit hashes for Security alerts

rust/experimental/query_abstraction/intermediate_language/src/grammar_objects.rs, rust/experimental/query_abstraction/intermediate_language/src/query_processor.rs, rust/experimental/query_abstraction/kql_plugin/src/kql_plugin.rs, rust/experimental/query_abstraction/ottl_plugin/src/ottl.pest, rust/experimental/query_abstraction/ottl_plugin/src/ottl_plugin.rs
This PR includes some incidental changes outside of just `KqlPlugin`
* Minor changes in `grammar_objects` to reduce overhead and expose needed members
* Addition of `QueryResult` and `QueryError` in `intermediate_language` to better follow Rust patterns around success and failure
The main bulk of the changes are in `KqlPlugin` which can now build full IL representation of `Filter` and `Extend` KQL queries. The fullest example of this may be found in `test_process_query_complex`:
```rust
let input = r#"my_table 
| where my_variable == 5
| where (x < 42) and (y > 24)
| where not(z >= 10)
| extend new_column = true, another_new_column = (another_variable == 100)
"#;
```
-->
```rust
// Full depth omitted for brevity
Query
├── Statement::Filter
|   └── Predicate::ComparisonExpression
| …
```
=> Implement process_query for KqlPlugin

README.md
Updated the contributing section to better align with other OpenTelemetry repositories.
Removed the license section as it is already covered on the repo home page:
=> Update the contributing section in the main README

.markdownlint.yaml, README.md
Follow up #335
Changes:
* Updated the rule to allow table and code blocks to bypass line-length limit
* Fixed the remaining markdownlint error
=> Fix markdownlint error

.github/workflows/go-ci.yml, .github/workflows/rust-audit.yml, .github/workflows/rust-ci.yml, .github/workflows/rust-experimental.yml, README.md, rust/README.md
Addresses #354
This PR splits the CI workflow steps performed for experimental projects versus the main core component.
Rust-CI
- test
- fmt
- clippy
- deny
- bench
- doc
- coverage (todo)
- custom xtask checks
Rust-Experimental
- test
- fmt
- clippy
- deny
=> Split experimental and core Rust CI

rust/experimental/syslog-cef-receivers/deny.toml, rust/experimental/syslog-cef-receivers/syslog-receiver/Cargo.toml, rust/experimental/syslog-cef-receivers/syslog-receiver/src/lib.rs
- Add tests for deserializing bytes into syslog messages
- I'm using [`syslog_loose`](https://crates.io/crates/syslog_loose) crate to parse the payload into [`Message`](https://docs.rs/syslog_loose/0.21.0/syslog_loose/struct.Message.html) struct. We could write our own parser for more efficient processing of these messages.
- The tests will anyway help us if we write our own parser in the future
=> [syslog-receiver] Add tests for syslog parsing

.github/workflows/rust-ci.yml, codecov.yaml, rust/otap-dataflow/README.md
Enable codecoverage for projects included in Rust-CI workflow. This only covers a small portion of the repository, but is a start.
Partially addresses #106.
=> Enable codecov in Rust-CI for core Rust component

README.md
Picked the correct link from the Otel calendar's meeting invite. The current link was pointing to the wrong location.
=> chore: Fix link to meeting notes

.github/workflows/repo-lint.yaml
Related to #373 - prep to handle that PR properly
Specifically, see [this comment](https://github.com/open-telemetry/otel-arrow/pull/373#discussion_r2076005379)
> Perhaps the convention is:
> * Operations that act on a specific subsection of code belong in \<Language\>-CI (since matrix list is already present there)
> * Operations that act on the repository as a whole (i.e. markdownlint and this sanitycheck script) can and should be combined together in Repo-Lint (or another name).
=> Rename docs-ci to repo-lint

rust/otap-dataflow/Cargo.toml, rust/otap-dataflow/README.md, rust/otap-dataflow/benchmarks/Cargo.toml, rust/otap-dataflow/benchmarks/README.md, rust/otap-dataflow/benchmarks/benches/config/main.rs
- Add benchmarks top level directory under otap-dataflow
- Criterion micro-benchmark definitions all located under benches/
- Eventual e2e load test definitions leveraging the testbed efforts in https://github.com/open-telemetry/otel-arrow/issues/377 in another subdirectory
- Add example benchmark test for otap-df-config::optimize_pipeline
Pipeline integrations and test-result persistence in future PRs.
=> [otap-dataflow] add criterion initial structure and benchmark test 

.github/workflows/go-ci.yml, .github/workflows/pipeline-perf-test.yml
Related to #289
I noticed an unexpected drop in [OpenSSF Scorecard results](https://scorecard.dev/viewer/?uri=github.com/open-telemetry/otel-arrow) - one of which is the Token-Permissions category.
Details include the following warnings:
> Warn: topLevel 'security-events' permission set to 'write': .github/workflows/go-ci.yml:5
Warn: no topLevel permission defined: .github/workflows/pipeline-perf-test.yml:1
This PR:
* Restricts `security-events: write` to single job in `Go-CI`
* Adds an explicit `contents: read` into `Pipeline Performance Tests` per best practice
=> Address regression in OpenSSF Token-Permissions

.github/workflows/go-ci.yml
This PR adds concurrency configuration to the Go-CI GitHub workflow (can expand to all other non-trivial CI checks, if all agree) to automatically cancel in-progress runs when new commits are pushed to the same PR or branch, as its pointless to continue the run when new code is pushed.
reference:
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
Similar effort in Otel Rust repo: https://github.com/open-telemetry/opentelemetry-rust/issues/2335
=> chore: Optimize workflows by cancelling stale runs

rust/otel-arrow-rust/src/otlp/attributes/store.rs, rust/otel-arrow-rust/src/otlp/logs.rs, rust/otel-arrow-rust/src/validation/otap.rs, rust/otel-arrow-rust/src/validation/otlp.rs, rust/otel-arrow-rust/src/validation/testdata.rs
Adds a validation test decoding logs from OTAP to OTLP.
Also corrects a few issues found in the decoder found by tests
- `log_attrs` columns `int` and `bytes` should be optional
- `from_logs` method should set the attributes on the Log record
=> test: added validation test for logs decoding otap to otlp

.github/workflows/rust-ci.yml, nextest.toml
- Add nextest as actions dependency
- Allow nextest to run tests but driven by cargo-llvm-cov
=> Use nextest for running tests via cargo-llvm-cov

go/pkg/otel/common/arrow/attributes.go, go/pkg/otel/common/otlp/attributes.go, go/pkg/otel/common/schema/schema.go, go/pkg/otel/metrics/arrow/exemplar.go, go/pkg/otel/metrics/otlp/exemplar.go, go/pkg/otel/traces/otlp/event.go, go/pkg/otel/traces/otlp/link.go, rust/otel-arrow-rust/src/otlp/attributes/decoder.rs, rust/otel-arrow-rust/src/otlp/attributes/parent_id.rs, rust/otel-arrow-rust/src/otlp/attributes/store.rs
Early in Phase 1, @lquerel did experiments with several attribute-set encoding schemes. We settled on a single strategy, but there is a bit of left-over in the implementation. This removes it in both Go and Rust implementations:
- Option to encode "delta_encoded" via schema metadata
- Choice of encoding mode "None" and "DeltaEncoding" are removed; the former "ParentIdDeltaGroupEncoding" remains
=> OTAP AttributeStore parent_id encoding cleanup

.github/renovate.json5
Renovate's Go dependency updates may fail and require manual intervention: [see this job run](https://github.com/open-telemetry/otel-arrow/actions/runs/15024100098/job/42220415019?pr=419) of #419.
>go: updates to go.mod needed; to update it:
go mod tidy
Renovate does support also running `go mod tidy` itself via opt-in config, see https://docs.renovatebot.com/golang/#module-tidying.
Hopefully merging this will lead to automatic Go dependency updates passing CI from the start.
**Note: Also did some `json` formatting in vscode, but only real content added are lines 32-36.**
=> Enable gomodTidy in Renovate config

rust/otel-arrow-rust/Cargo.toml
Manual replacement for #460 and #461. Those Renovate PRs don't pass CI because the upgrades must be done together.
An inner dependency of Arrow had a breaking change - for more information see [arrow-rs #7196](https://github.com/apache/arrow-rs/issues/7196).
=> Upgrade arrow and arrow-ipc to v55

tools/pipeline_perf_test/orchestrator/lib/process/deployed_process/docker.py, tools/pipeline_perf_test/orchestrator/lib/process/utils/docker.py, tools/pipeline_perf_test/orchestrator/orchestrator.py
This PR switches out the subprocess based docker CLI calls to use the python docker api client library. A new flag is added to enable printing equivalent CLI commands for all interactions to assist with debugging.
Functionality should be equivalent to previous version, biggest change is moving away from the string based process metrics parsing and relying on the stats api results directly.
Small additional refactor to group any image building as the first step to make client initialization logic more friendly.
=> Perf - switch docker interaction to use api client library

tools/pipeline_perf_test/orchestrator/lib/core/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/context/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/context/base.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_context.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_definition.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_step.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_suite.py
This is the first of several PRs that will perform additional refactoring on the orchestrator module, with the goal being to enhance / standardize the test and component orchestration and related control flows. The diagram below lays out roughly the planned structure (we'll continue to iterate on this). The first PR includes core Test*/Context models (left side of the diargram). The next PR will introduce the component / strategy models. And a final PR(s) will migrate the existing functionality over to this new structure.
=> Perf - Orchestrator restructuring phase1

tools/pipeline_perf_test/orchestrator/lib/core/component/lifecycle_component.py, tools/pipeline_perf_test/orchestrator/lib/core/component/runtime.py, tools/pipeline_perf_test/orchestrator/lib/core/context/base.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/configuration_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/deployment_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/execution_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/monitoring_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_context.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_definition.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_step.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_suite.py, tools/pipeline_perf_test/orchestrator/lib/impl/__init__.py, tools/pipeline_perf_test/orchestrator/lib/impl/component/__init__.py, tools/pipeline_perf_test/orchestrator/lib/impl/component/managed_component.py, tools/pipeline_perf_test/orchestrator/lib/impl/strategies/__init__.py, tools/pipeline_perf_test/orchestrator/lib/impl/strategies/deployment/__init__.py, tools/pipeline_perf_test/orchestrator/lib/impl/strategies/deployment/docker.py, tools/pipeline_perf_test/orchestrator/requirements.txt
Sorry about the size... wanted to include a couple implementations to illustrate how things will fit together (can trim them out and focus on the core changes if preferred).
- Refactor contexts to support various plugin needs (store clients, additional helper methods, basic logging / timing / state support)
- Add component runtime data registry to support component scoped info that crosses test / step / hook bounds (e.g. container / process IDs).
- Added pydantic for configuration spec / validation.
- Add ManagedComponent implementation of Lifecycle component (other might include static component for e.g. long lived cloud services) - implements all the lifecycle methods and invokes hooks.
- Add example docker deployment strategy with dummy methods that approximate the data needs of the …
=> Perf - Orchestrator context refactor and component implementation

tools/pipeline_perf_test/orchestrator/lib/process/utils/kubernetes.py, tools/pipeline_perf_test/orchestrator/orchestrator.py
K8s mod was trying to build the image, but this is already done by orchestrator and just needed to pass image name.
=> PipelinePerfTest - nit fix to k8s path

tools/pipeline_perf_test/orchestrator/lib/core/component/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/component/component.py, tools/pipeline_perf_test/orchestrator/lib/core/component/component_data.py, tools/pipeline_perf_test/orchestrator/lib/core/context/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/context/base.py, tools/pipeline_perf_test/orchestrator/lib/core/context/component_hook_context.py, tools/pipeline_perf_test/orchestrator/lib/core/context/test_contexts.py, tools/pipeline_perf_test/orchestrator/lib/core/context/test_element_hook_context.py, tools/pipeline_perf_test/orchestrator/lib/core/runtime/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/runtime/runtime.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_data.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_definition.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_element.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_step.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_suite.py
This change refactors hook and runtime classes and adds support for them on Test Elements (Test Suite, Test, Test Step).  This will allow us to e.g. run global hooks in order to e.g. deploy infrastructure without having to tie it to a particular component. Change also includes restructuring to provide more uniformity between component and test element naming, and introduces  base classes for test elements and their associated context classes.
- Rename LifecycleComponent -> Component
- Rename LifecyclePhase -> ComponentPhase
- Rename HookableLifecyclePhase -> HookableComponentPhase
- Rename LifecycleHookContext -> ComponentHookContext
- Move ComponentHookContext, HookableComponentPhase -> lib.core.context
- Rename ComponentRuntime -> Runtime 
- Move Runtime to lib.core.runtime (new).
- Add …
=> Perf - support hook execution and runtime data on test framework elements.

.github/workflows/pipeline-perf-test.yml
Manual replacement for #492
In order to properly update on SemVer release instead of every commit with embedded changelog, need the fully qualified `v4.3.0` on the end.
=> Pin actions/download-artifact to SemVer hash

tools/pipeline_perf_test/orchestrator/lib/core/context/base.py, tools/pipeline_perf_test/orchestrator/lib/core/context/component_hook_context.py, tools/pipeline_perf_test/orchestrator/lib/core/context/test_contexts.py, tools/pipeline_perf_test/orchestrator/lib/core/context/test_element_hook_context.py
The PR adds support for tracing / logging / metrics in the various framework context objects.
E.g. automatic creation / end of spans with status, ability to fetch otel tracers, meters, and logging handler inside plugins, decorating spans with ctx metadata, and generating span events.
=> Perf - Add otel supporting functionality to framework context objects

tools/pipeline_perf_test/orchestrator/lib/core/component/component.py, tools/pipeline_perf_test/orchestrator/lib/core/component/component_data.py, tools/pipeline_perf_test/orchestrator/lib/core/errors/__init__.py, tools/pipeline_perf_test/orchestrator/lib/core/errors/error_handler.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/base.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/configuration_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/deployment_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/execution_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/hook_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/monitoring_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/strategies/reporting_strategy.py, tools/pipeline_perf_test/orchestrator/lib/core/telemetry/log.py, tools/pipeline_perf_test/orchestrator/lib/core/telemetry/test_event.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_data.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_definition.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_element.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_step.py, tools/pipeline_perf_test/orchestrator/lib/core/test_framework/test_suite.py
This adds the actual logging and span instrumentation to core test components, and introduces centralized plugin error handling. Misc config base models, and other accumulated nit/todo fixes as well.
=> Perf - remaining core telemetry support

CHANGELOG.md, collector/cmd/otelarrowcol/main.go, collector/otelarrowcol-build.yaml, go.mod, versions.yaml
Next step of https://github.com/open-telemetry/otel-arrow/issues/566 involves:
- Retract `v0.37.0` due to incompatibility with consumers (OpenTelemetry-Collector-Contrib)
- Mark terminal version of `github.com/open-telemetry/otel-arrow` module with deprecation notice
- Bump version to `v0.38.0`
=> Mark terminal version of otel-arrow module and bump to 0.38.0

pkg/benchmark/dataset/synthetic_dataset.go, pkg/datagen/data_generator.go, pkg/otel/arrow_record/producer_consumer_test.go, pkg/otel/logs/validation_test.go, pkg/otel/metrics/validation_test.go, pkg/otel/traces/validation_test.go, tools/logs_gen/main.go, tools/metrics_gen/main.go, tools/trace_gen/main.go
Attempt at addressing #529
According to various [codecov readings](https://app.codecov.io/gh/open-telemetry/otel-arrow/pull/554/indirect-changes), the discrepancy in our codecov is often in various error conditions of different `pkg/otel` files.
This PR was a result of a brief look into the test infrastructure there and noting several usages of `rng` with a seed of type `rand.Uint64`. Out of curiosity I removed them and ran checked coverage multiple times locally, and found it stabilizes at reproducible numbers.
I am not entirely sure how important true entropy is in testing the go modules compared to seeded entropy, looking for insights from @jmacd and @lquerel who wrote most of it.
=> Remove randomness in go tests to address flaky codecov

rust/experimental/query_engine/engine-recordset/src/primitives/any_value.rs, rust/experimental/query_engine/engine-recordset/src/primitives/mod.rs
* Define `AnyValue` enum to expose primitives in recordset query engine
=> [query-engine] Add AnyValue enum to recordset engine

rust/experimental/query_engine/engine-recordset/src/transform_expressions/clear_transformation_expression.rs, rust/experimental/query_engine/engine-recordset/src/transform_expressions/mod.rs, rust/experimental/query_engine/engine-recordset/src/transform_expressions/move_transformation_expression.rs, rust/experimental/query_engine/engine-recordset/src/transform_expressions/remove_transformation_expression.rs, rust/experimental/query_engine/engine-recordset/src/transform_expressions/set_transformation_expression.rs, rust/experimental/query_engine/engine-recordset/src/transform_expressions/transformation_expression.rs
* Adds basic transformation expressions (set, remove, move, clear) into recordset engine
=> [query-engine] Add basic transformation expressions into recordset engine

rust/experimental/query_engine/engine-recordset/src/value_expressions/mod.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions/resolve_from_attached_value_expression.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions/resolve_value_expression.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions/static_value_expression.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions/value_expression.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions/variable_value_expression.rs
* Adds basic value expressions (resolve, resolve_from_attached, static, variable) into recordset engine
=> [query-engine] Add basic value expressions to the recordset engine

rust/experimental/query_engine/expressions/src/expression.rs, rust/experimental/query_engine/kql-parser/src/kql_parser.rs
Following up on https://github.com/open-telemetry/otel-arrow/pull/578#discussion_r2140465595
* Allow expression validation in tests with fake query locations
=> [query-engine] Allow fake query locations in expression tests

rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/kql_parser.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Support parsing KQL project expression onto `Set` & `Clear` transformations
* Add the raw query string to `ParserState` and a helper for getting query slice from a `QueryLocation`
=> [query-engine] Add clear transformation and support for parsing KQL project expressions

.gitignore, tools/pipeline_perf_test/orchestrator/orchestrator.py
- added `--kind-cluster` option that accepts cluster name as a value, if passed without a value it will use `kind` as the cluster name, if not passed, doesn't use kind cluster.
- added `--install-metrics-server`, works with kubernetes option, installs metrics server on the cluster with insecure TLS for dev purposes.
=> orchestrator.py auto load to kind cluster option and install metrics server option for convnience

rust/experimental/query_engine/kql-parser/src/kql_parser.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
=> [query-engine] Refactor ParserState to not expose fields

rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/kql_parser.rs
* Support parsing `project-away` KQL expressions onto `Remove` & `RemoveKeys` transformations
=> [query-engine] Parse KQL project-away onto Remove & RemoveKeys expressions

pkg/benchmark/compression.go
Potential fix for [https://github.com/open-telemetry/otel-arrow/security/code-scanning/1](https://github.com/open-telemetry/otel-arrow/security/code-scanning/1)
To fix the problem, we need to ensure that the size computation for the allocation does not overflow. This can be achieved by validating the size of `data` before performing the multiplication. If the size of `data` is too large, we should return an error to prevent the overflow.
1. Add a check to ensure that `len(data)` is within a safe range before performing the multiplication.
2. If `len(data)` exceeds the safe range, return an error indicating that the data is too large to process.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Potential fix for code scanning alert no. 1: Size computation for allocation may overflow

rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/expressions/src/value_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql_parser.rs
Follow-up to https://github.com/open-telemetry/otel-arrow/pull/615#discussion_r2155476636
* Add doc comments where it was missing on expression definitions
* Rename Clear -> ClearKeys to fit in better with RemoveKeys
=> [query-engine] Rename Clear -> ClearKeys and add doc comments

rust/experimental/query_engine/expressions/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/kql_parser.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Harden the KQL parsing of `extend`, `project`, `project-keep`, and `project-away` expressions to prevent referencing the top-level thing
Previously these were allowed but are nonsensical:
```
extend source = [expression]
project source
project source = [expression]
project-away source
project-keep source
```
=> [query-engine] Harden the kql parsing of project statements

rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql_parser.rs
* Introduce `ReduceMap` expression and use that to drive KQL `project` expressions
My first attempt at this was #620. Worked fine for map accessors. Could work for array accessors. But those are statically known in the query. What I realized is that design would just not work at all for accessors which reference something that is not known until evaluation. For example `body[my_variable]` could resolve a string (map key) or int (array index) or some other scalar (error).
What this PR is doing is adding a `ReduceMap` operation which is able to express a) patterns, b) static keys, and c) accessor expressions. My plan is to use this for `project`, `project-keep`, and `project-away` and then remove `ClearKeys`.
=> [query-engine] Introduce ReduceMap expression and update KQL project

rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql_parser.rs
Follow-up to #627
* Update `project-away` and `project-keep` KQL expressions to use `ReduceMap` expression
* Remove `ClearKeys` expression
=> [query-engine] Update KQL project-keep and project-away to use ReduceMap

.github/renovate.json5
#624 had an invalid Renovate config - `ignorePaths` doesn't go inside `packageRules`. 
Used [Renovate Config Validator tool](https://docs.renovatebot.com/config-validation/#config-validation) to prove this fix locally.
Opened #635 to track work to avoid recurrence of this problem.
Fixes #630.
=> Properly place Renovate ignorePaths config

rust/experimental/query_engine/expressions/src/lib.rs, rust/experimental/query_engine/expressions/src/pipeline_expression.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/kql_parser.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Support parsing KQL `let` expressions as `Set` transformations
* Add top-level query parsing onto `PipelineExpression`s
=> [query-engine] Parse KQL let expression and query statements

rust/experimental/query_engine/expressions/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/static_scalar_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs
* Allow full scalar expressions inside accessor expressions when parsing KQL
=> [query-engine] Allow scalar expressions in accessor expressions when parsing KQL

rust/experimental/query_engine/expressions/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/static_scalar_expressions.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs
* Remove the `to_value` code and replace it with `try_resolve_value_type`
I felt `to_value` was too restrictive for what was needed. It would return full values which really only works for static expressions. Consider something like `tolong([scalar])` or `tostring([scalar])`. With the new design we can determine the correct value type without having to evaluate the inner expressions at all. The value type is really all that is needed for the validation code calling this API. Full static values can still be resolved using `try_resolve_static`.
=> [query-engine] Refactor the code used to determine the value type of scalar expressions

CONTRIBUTING.md, README.md
See [community #2830](https://github.com/open-telemetry/community/issues/2830) - ask is to clearly display repository maintainer/approver teams on Readme.
=> [Editorial] Standardize README content to include repository maintainers and approvers

rust/experimental/query_engine/expressions/Cargo.toml, rust/experimental/query_engine/expressions/src/expression_error.rs, rust/experimental/query_engine/expressions/src/lib.rs, rust/experimental/query_engine/expressions/src/primitives/mod.rs, rust/experimental/query_engine/expressions/src/primitives/value.rs, rust/experimental/query_engine/expressions/src/primitives/value_type.rs, rust/experimental/query_engine/expressions/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/static_scalar_expressions.rs
* Add a `Value` API in expressions which can evaluate comparison and equality logic
The goal here is to use this 'Value' API to evaluate expressions at compile-time (constant folding) and in recordset & columnar engines at runtime. Not sure exactly how this will work with Arrow + DataFusion in columnar engine (need to spend some time there exploring & prototyping) but that is the goal 😄
=> [query-engine] Add value comparison and equality logic in expressions

rust/experimental/query_engine/expressions/Cargo.toml, rust/experimental/query_engine/expressions/src/lib.rs, rust/experimental/query_engine/expressions/src/primitives/value.rs, rust/experimental/query_engine/expressions/src/primitives/value_type.rs, rust/experimental/query_engine/expressions/src/static_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_conditional_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/shared_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Remove constant folding of scalar expressions inside KQL parser
* Introduce regex static value and use that for pattern matching in key lists
I'm working on running the new `PipelineExpression` in the recordset engine. The constant folding has some issues. It works fine generally but how things fold the query location for the USE of the constant is lost and only the constant definition location is retained. This makes proper diagnostics impossible. Also we _always_ copy the constant. For large constants (maps, arrays, big strings) we probably don't want to make those copies and instead perform a lookup to the constant definition. To address this constant folding really needs to move from KQL Parser into Expressions proper. I'll do that as a follow-up. The big benefit to do that besides …
=> [query-engine] Introduce Regex + remove constant folding in KQL parser

rust/otap-dataflow/crates/otap/src/encoder.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/common.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/decode.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/logs.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/resource.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/proto/common.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/proto/logs.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/proto/resource.rs, rust/otap-dataflow/crates/pdata-views/src/views/common.rs
A few micro-optimizations for the view implementations
- Use `&str` instead of `Cow<'a,str>` 
- Add `#[inline]` to all the methods that are used when encoding data to OTAP
- For the bytes implementation, update the `advance_to_find_field` method to
- Enter the loop only if the field is not already cached
- Use a simpler check `field == field_num` instead of calling `get_field_range` to know when to return
I made the first two changes to both the prost and the bytes implementation to have a fair comparison.
For the bytes representation, these changes showed a ~5% improvement in the traversal benchmarks and ~3.5% for the encoding benchmarks.
=> [otap-dataflow] Micro optimizations for the view implementations

rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/expressions/src/pipeline_expression.rs, rust/experimental/query_engine/expressions/src/primitives/value_type.rs, rust/experimental/query_engine/expressions/src/scalar_expressions.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs, rust/experimental/query_engine/parser-abstractions/src/parser_error.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
Relates to #684
* Support constants in expressions
This solves the issue mentioned on #684 where we previously lost the information about WHERE constants were referenced in the expression tree. Now the tree owns the constants and understands where they are being used.
Note: This PR does not bring back constant folding. Currently referenced constants are always a lookup operation. In a follow-up PR I'll bring back (among other things) constant folding where small constants get copied where they are used (to avoid the lookup cost).
=> [query-engine] Support constants in expressions

.github/renovate.json5
Updates Renovate config to reduce the number of Docker Digest PRs we get. Since these don't follow SemVer, Renovate spawns a PR for every push (see #681, #679, #678, #676, #675, #589, etc). It should be fine to group these together on a regular schedule.
=> Schedule monthly docker digest updates with Renovate

rust/experimental/query_engine/kql-parser/src/lib.rs, rust/experimental/query_engine/ottl-parser/src/lib.rs
* Re-export `Parser` & `ParserError` in kql and ottl parser crates
We have this [Parser](https://github.com/open-telemetry/otel-arrow/blob/4f55ba7eb4abfe5f57177d15603df0e86b23f47a/rust/experimental/query_engine/parser-abstractions/src/parser.rs#L7) trait which is the entry point for parsing KQL or OTTL queries.
In order to call these traits users have to bring them into scope which currently means depending on the `parser-abstractions` crate. What this change does is makes them part of the public API in the KQL & OTTL crates so users don't need to worry about `parser-abstractions`.
I feel like this is a good thing to do but I'm also new to Rust 😄 It may be something which gets reverted later but I thought it was worth trying out.
=> [query-engine] Re-export Parser API in parser crates

rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/mod.rs, rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Moved `ResolvedStaticScalarExpression` to its own file in expressions
* Tweaked `ResolvedStaticScalarExpression` API to use the `Value` API instead of interacting with `StaticScalarExpression` directly
* Made a lot of the static resolution API internal
Really just some random cleanup and refactoring I've done while working on getting expressions up and running in recordset engine.
=> [query-engine] Refactor static resolution API

rust/otap-dataflow/Cargo.toml, rust/otap-dataflow/benchmarks/benches/otap_encoder/main.rs, rust/otap-dataflow/crates/otap/Cargo.toml, rust/otap-dataflow/crates/otap/src/encoder.rs, rust/otap-dataflow/crates/otap/src/encoder/cbor.rs, rust/otap-dataflow/crates/otap/src/encoder/error.rs, rust/otap-dataflow/deny.toml, rust/otel-arrow-rust/Cargo.toml, rust/otel-arrow-rust/src/encode/record/array.rs, rust/otel-arrow-rust/src/encode/record/array/binary.rs, rust/otel-arrow-rust/src/encode/record/array/boolean.rs, rust/otel-arrow-rust/src/encode/record/array/dictionary.rs, rust/otel-arrow-rust/src/encode/record/array/fixed_size_binary.rs, rust/otel-arrow-rust/src/encode/record/array/prefix.rs, rust/otel-arrow-rust/src/encode/record/array/primitive.rs, rust/otel-arrow-rust/src/encode/record/array/string.rs, rust/otel-arrow-rust/src/encode/record/logs.rs
**Benchmark improvements:**
- Adds a variety of batch sizes to the `otap_encoder` benchmark
**Performance improvements**
- Adaptive Array Builders:
- Adds new methods to append multiple values to the array builders in a single method call. This is 
- Use the optimized `append_nulls` implementation that was introduced in arrow-rs v52.2 https://github.com/apache/arrow-rs/pull/7606
- Uses a macro to handle the append value logic instead of a method with callbacks instead of the generic `handle_append` method that took callback arguments. This improves performance on the hot path of `AdaptiveArrayBuilder::append_value / append_slice / etc.`
- Add additional inlines for some short, frequently called methods
- Array/KvList value serialization:
- optimize CBOR serialization to remove heap …
=> [perf] additional performance improvements for OTAP encoding

rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/shared_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Store variable and attached record names as `StringScalarExpression`s
Doing this allows them to be accessed using the `Value` API (like other things which also come from the query) and adds the location tracking for diagnostics
=> [query-engine] Store variable and attached record names as StringScalarExpressions

rust/otap-dataflow/crates/pdata-views/src/otlp/proto.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/proto/trace.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/proto/wrappers.rs
Generating reference wrappers and iterators for OTLP views is tedious, so this change introduces generic wrappers and iterators to cut the tedium (this makes life much easier in the next PR I'm going to submit which adds OTLP protobuf struct to OTAP conversion for metrics). I've updated the recently added views for traces (but not logs or common) to make use of these wrappers.
=> feat: add generic wrappers support OTLP view generation

rust/experimental/query_engine/engine-recordset2/src/transform/reduce_map_transform_expression.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/lib.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs, rust/experimental/query_engine/ottl-parser/src/lib.rs, rust/experimental/query_engine/parser-abstractions/src/parser.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
Fixes #685
* Introduces schema for the source record when parsing expressions
* Support inner regex patterns in reduce map
=> [query-engine] Add schema support to query engine parsers and support inner regex in reduce map

tools/pipeline_perf_test/load_generator/loadgen.py, tools/pipeline_perf_test/load_generator/tests/test_config.py, tools/pipeline_perf_test/load_generator/tests/test_flask_api.py, tools/pipeline_perf_test/load_generator/tests/test_log_record.py, tools/pipeline_perf_test/load_generator/tests/test_worker_thread.py, tools/pipeline_perf_test/load_generator/tox.ini
This PR introduces an optional "target_rate" flag / config item that will cause the loadgenerator worker threads to attempt to hit a specific rate of messages/sec. Default behavior in cli / server mode is unchanged.
- Add "target_rate" cli argument and config field, which will throttle threads when set
- Add "late_batches" metric for tracking where sends are failing to reach the target rate
- Add logic to compute per-worker-thread send intervals, and apply simple sleep based throttles
- Add light testing for configs, message format, worker behavior, and flask server
Support for orchestrator execution strategy to specify rate limiting will come in a subsequent PR
=> [Perf] add optional load_generator rate limit

.github/workflows/prepare-release.yml, .github/workflows/push-release.yml, .github/workflows/scripts/create-release-branch.sh, .github/workflows/scripts/extract-changelog.sh, .github/workflows/scripts/get-last-version.sh, .github/workflows/scripts/update-changelog.sh, .github/workflows/scripts/validate-version-increment.sh, .github/workflows/scripts/validate-version.sh
Fixes after [first run of prepare-release workflow](https://github.com/open-telemetry/otel-arrow/actions/runs/16528210761/job/46746812345), follow-up to #739
- Use `fetch-tags` during checkout
- Fix changelog content addition (don't override start of file headers)
- Use scripts instead of inline to enable local testing
- Address security warnings:
- Use joblevel permissions instead of toplevel
- Pin `create-github-app-token` action to Hash version
=> Minor prepare-release fixes and script abstraction

rust/otap-dataflow/Cargo.toml, rust/otap-dataflow/crates/engine/src/effect_handler.rs
Follow-up to #785 
- Fix import of `tokio::io::stdout` in effect handler's `info` method
=> Fix import

rust/otap-dataflow/crates/engine/src/exporter.rs, rust/otap-dataflow/crates/engine/src/message.rs, rust/otap-dataflow/crates/engine/src/testing/exporter.rs, rust/otap-dataflow/crates/otap/src/otap_exporter.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter.rs, rust/otap-dataflow/crates/otap/src/pdata.rs, rust/otap-dataflow/crates/otap/src/perf_exporter/exporter.rs, rust/otap-dataflow/crates/otlp/src/debug_exporter/exporter.rs, rust/otap-dataflow/crates/otlp/src/otlp_batch_processor.rs, rust/otap-dataflow/crates/otlp/src/otlp_exporter.rs
fixes: https://github.com/open-telemetry/otel-arrow/issues/759
Fixes the flakey shutdown timeout test in parquet_exporter.
Before this change, the test was passing a `ControlMsg::Shutdown(Duration::ZERO)`, which would cause the channel to send a shutdown message to the exporter without trying to drain pdata. Most of the time, this would mean that calling `writer.flush()` would instantly finish because there were no buffered writes, and we wouldn't hit the timeout error. But occasionally, the timeout future would complete first for some reason and the test would fail.
Obviously we want to make this more reliable, while also testing the proper timeout behaviour. To do this, we need to invoke the drain mechanism to buffer some writes, in order that parquet exporter's `writer.flush()` method …
=> fix: flakey shutdown timeout test

tools/pipeline_perf_test/backend/backend.py, tools/pipeline_perf_test/backend/tests/test_receiver.py, tools/pipeline_perf_test/orchestrator/lib/impl/strategies/execution/pipeline_perf_loadgen.py, tools/pipeline_perf_test/orchestrator/lib/impl/strategies/hooks/reporting/pipeline_perf_report.py, tools/pipeline_perf_test/test_suites/dataflow_engine_e2e_logs/README.md, tools/pipeline_perf_test/test_suites/dataflow_engine_e2e_logs/collector-config-without-batch-processor.yaml, tools/pipeline_perf_test/test_suites/dataflow_engine_e2e_logs/test-suite-comparison.yaml
This adds an initial perf test suite for the single-threaded, un-optimized, dataflow engine to compare otlp logs performance with the go collector running in a similar configuration. It includes a few small fixes to backend / orchestrator to support additional knobs needed.
- add test_suites/dataflow_engine_e2e_logs - workflow with constant rate (100k log/sec) load to the dataflow engine and otel collector with comparable configuration.
- Add support for constant rate log generation in orchestrator's pipeline_perf log exection strategy.
- Add support for env based port selection in backend.py to support dataflow engine example default otlp out port.
- Fix missing await in backend.py shutdown handler
- Fix pipeline perf report to provide more accurate send/receive avg rate calculations. …
=> [PerfTest] Perf Test Suite for dataflow engine otlp logs

rust/otap-dataflow/benchmarks/Cargo.toml, rust/otap-dataflow/benchmarks/benches/retry_processor/main.rs, rust/otap-dataflow/crates/engine/Cargo.toml, rust/otap-dataflow/crates/engine/src/lib.rs, rust/otap-dataflow/crates/engine/src/retry_processor.rs
(This is a refactored version after the EffectHandler, etc changes in #532)
Add RetryProcessor with Testing and Benchmarks
Summary
Adds a new RetryProcessor component that provides reliable message delivery with exponential backoff retry logic for the OTAP dataflow engine.
Changes
•  New RetryProcessor: Handles message retries with configurable policies, ACK/NACK feedback, and graceful shutdown
•  9 comprehensive unit tests: Cover all major functionality including retry logic, backpressure, and edge cases  
•  Performance benchmarks: Microbenchmarks showing ~150-230ns latency for core operations
Key Features
•  Exponential backoff with configurable limits (default: 3 retries, 1s initial delay)
•  ACK/NACK message tracking with HashMap-based O(1) operations
•  Queue limits for backpressure …
=> Feature retry processor (v2)

rust/experimental/query_engine/engine-recordset2/src/logical_expressions.rs, rust/experimental/query_engine/engine-recordset2/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs
Relates to #722
* Adds support for `=~` and `!~` KQL operators
=> [query-engine] Support KQL case-insensitive equality

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/lib.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/mod.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/protobuf_reader.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/protobuf_writer.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/serializer_error.rs
* Adds code to read & write protobuf messages
This will be used in the bridge to take protobuf OTLP messages and deserialize them directly onto structs the query engine can process natively and then serialize the results as protobuf OTLP messages on the way out.
=> [query-engine] Add protobuf reader and writer to bridge

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/lib.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/collector_logs.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/common.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/logs.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/mod.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/resource.rs
* Add OTLP structs matching proto layout in bridge
The idea here is to parse OTLP protobuf manually onto these structs and then hand them into the engine.
=> [query-engine] Add OTLP structs matching proto layout in bridge

rust/experimental/query_engine/engine-recordset2/src/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/convert_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs
Relates to #722
* Adds `LengthScalarExpression` support in expressions and recordset engine
* Adds logging to execution logic for `ConvertScalarExpression` in recordset engine
=> [query-engine] Add length scalar expression

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/attached_records.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/lib.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/logs.rs
* Implements the contract required to run recordset engine on the OTLP receiver structs in the bridge crate
=> [query-engine] Implement the recordset engine contract in bridge

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/attached_records.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/bridge.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/logs.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/common.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/logs.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/otlp_reader.rs, rust/experimental/query_engine/engine-recordset-otlp-bridge/src/serializer/otlp_writer.rs, rust/experimental/query_engine/engine-recordset/src/engine.rs, rust/experimental/query_engine/engine-recordset/src/primitives/owned_value.rs, rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs, rust/experimental/query_engine/engine-recordset/src/primitives/value_mut.rs, rust/experimental/query_engine/engine-recordset/src/primitives/value_storage.rs, rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/test_helpers.rs, rust/experimental/query_engine/engine-recordset/src/transform/reduce_map_transform_expression.rs, rust/experimental/query_engine/engine-recordset/src/transform/transform_expressions.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions.rs, rust/experimental/query_engine/expressions/src/primitives/array_value.rs, rust/experimental/query_engine/expressions/src/primitives/map_value.rs, rust/experimental/query_engine/expressions/src/primitives/value.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/array_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/map_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/transform_expressions.rs
* Rename `Value` and `ValueMut` -> `StaticValue` & `StaticValueMut`
* Re-introduce `Value` without `'static` requirement
* Use `From` \ `Into` for conversions instead of custom logic on `ValueSource<T>`
* Use blanket implementations of traits where possible to allow removal of a lot of code repating boilerplate things like `impl AsValue for [SomeType] { ... }`
The main thing this addresses is the `'static` on `Value`...
```rust
enum Value<'a>
{
Array(&'a (dyn ArrayValue + 'static))
...
}
```
The `'static` there means the thing implementing the trait must be statically-known. It doesn't mean it needs a 'static` lifetime. One of the restrictions for something to be known statically is that it can't itself have a lifetime or contain any pointers.
What I'm working on is slice support in the …
=> [query-engine] Static value refactor

rust/experimental/query_engine/engine-recordset/src/logical_expressions.rs, rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions.rs, rust/experimental/query_engine/expressions/src/primitives/value.rs, rust/experimental/query_engine/expressions/src/scalars/convert_scalar_expression.rs
* Reverts [this change](https://github.com/open-telemetry/otel-arrow/pull/829/files#diff-4ba0898c86bce0156158c29e56edd36aabc32a52dbbfd8884b38e6e4db43a499R97) which caused `null` to be indistinguishable from empty string in logging. Instead added special handling in `tostring` logic to resolve `null` as empty string.
* Adds `''` around values in "Evaluated as: {...}" logging to improve clarity
=> [query-engine] Logging tweaks

rust/otel-arrow-rust/Cargo.toml, rust/otel-arrow-rust/src/otap.rs
Ran into a stack overflow when poking around with multivariate metrics types, I think the intent is for the types to be the same as Univariate for now, but let me know if not.
=> fix: Stack overflow when getting child types for multivariate metrics

rust/otap-dataflow/crates/engine/src/control.rs, rust/otap-dataflow/crates/engine/src/message.rs, rust/otap-dataflow/crates/otap/src/perf_exporter/config.rs, rust/otap-dataflow/crates/otlp/src/compression.rs, rust/otap-dataflow/crates/otlp/src/debug_exporter/config.rs, rust/otap-dataflow/crates/otlp/src/fake_signal_receiver/config.rs, rust/otap-dataflow/crates/pdata-views/src/views/metrics.rs
- Use `const` methods when possible
Making these methods const provides several benefits:
- Compile-time evaluation: These methods can now be evaluated at compile time when called with const arguments
- Performance: Potentially better optimization by the compiler
- API clarity: Signals to users that these methods are pure functions with no side effects
- Future-proofing: Ready for more advanced const evaluation features in future Rust versions
=> [otap-dataflow] Use const methods when possible

rust/otap-dataflow/crates/engine/src/local/processor.rs, rust/otap-dataflow/crates/engine/src/local/receiver.rs, rust/otap-dataflow/crates/engine/src/shared/processor.rs, rust/otap-dataflow/crates/engine/src/shared/receiver.rs
- Receivers and Processors would send the messages to the next component in the pipeline using `EffectHandler::send_message` method
- This PR optimizes the send methods for both `local` and `shared` receiver and processor's effect handlers
- Avoid `Hashmap` lookup on the hot-path by caching the default sender
- Avoid cloning the port name for each send operation by using references
- Avoid cloning the sender for send operation by using references
=> [perf] [hot-path] Optimize send_message methods on EffectHandler

rust/otap-dataflow/crates/otap/src/perf_exporter/exporter.rs
Related to #927.
This PR updates the perf exporter calculations:
- Count otlp signals instead of bytes
- Increment total counters by current batch/signal size instead of accumulated batch/signal size for this interval on each new batch.
Will update tests in a subsequent PR (planning to move some code in parquet-exporter/tests around to support this, so splitting it up to keep it more manageable).
=> [perf-exporter] fix perf otlp signal counting

rust/otap-dataflow/crates/otap/src/otap_exporter.rs
Fixes #933 
This PR implements config of the OTAP exporter from file / config object.
=> [otap-dataflow] implement configuration of OTAP exporter from config object

rust/otap-dataflow/crates/otap/src/fixtures.rs, rust/otap-dataflow/crates/otap/src/lib.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/idgen.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/writer.rs, rust/otap-dataflow/crates/otap/src/perf_exporter/README.md, rust/otap-dataflow/crates/otap/src/perf_exporter/exporter.rs
Fixes #927.
This PR moves the parquet_exporter/test/datagen.rs code into the main otap library for shared test fixtures.
- Added header generation via options to all create_simple_*_arrow_record_batches functions
- Added config option for timestamp header generation (default true)
- Refactor of the perf_exporter tests to leverage the new fixtures.
=> [otap-dataflow] move otap datagen test files to fixtures.rs and perf exporter test refactor

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/logs.rs, rust/experimental/query_engine/engine-recordset/src/engine.rs, rust/experimental/query_engine/engine-recordset/src/test_helpers.rs
* Remove unused timestamp fields from `Record` trait
=> [query-engine] Remove unused timestamp fields from Record trait

go/pkg/otel/logs/otlp/logs.go, go/pkg/otel/logs/validation_test.go
=> fix: golang OTAP decoding logs handles optional trace ID and span ID columns

rust/otap-dataflow/crates/otap/src/fake_data_generator.rs, rust/otap-dataflow/crates/otlp/src/fake_signal_receiver/attributes.rs, rust/otap-dataflow/crates/otlp/src/fake_signal_receiver/receiver.rs
Fixes test issue described in https://github.com/open-telemetry/otel-arrow/issues/964
caused by formatted key in attributes.rs which led to a comparison fail when checking attributes against the resolved registry
=> [otap-dataflow] Fix broken test otap-df-{otlp,otap} test_fake_signal_receiver()

rust/otap-dataflow/crates/engine/src/control.rs, rust/otap-dataflow/crates/engine/src/effect_handler.rs, rust/otap-dataflow/crates/engine/src/node.rs, rust/otap-dataflow/crates/engine/src/pipeline_ctrl.rs, rust/otap-dataflow/crates/engine/src/runtime_pipeline.rs
Follow up to https://github.com/open-telemetry/otel-arrow/pull/939#discussion_r2286670031
- Update Node index to `usize` to look up the vec directly without converting from `u16`
=> Update Node index to usize

rust/otap-dataflow/crates/otap/src/encoder.rs, rust/otap-dataflow/crates/otap/src/pdata.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/common.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/consts.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/decode.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/logs.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/resource.rs, rust/otap-dataflow/crates/pdata-views/src/otlp/bytes/traces.rs, rust/otel-arrow-rust/src/encode/record/traces.rs, rust/otel-arrow-rust/src/otlp/traces.rs, rust/otel-arrow-rust/src/otlp/traces/span_event_store.rs, rust/otel-arrow-rust/src/otlp/traces/span_links_store.rs, rust/otel-arrow-rust/src/otlp/traces/spans_arrays.rs
Resolves: https://github.com/open-telemetry/otel-arrow/issues/388 
Part of: https://github.com/open-telemetry/otel-arrow/issues/878
Changes:
- Implements the PData Views for Traces for OTLP bytes messages
- Implements the conversion from OTLP Bytes for Traces pdata
- Handle the plain encoded IDs when decoding Traces OTAP batches to OTLP
=> Add decoding of OTAP Traces from OTLP Bytes

rust/otap-dataflow/crates/otap/src/parquet_exporter.rs
Fixes: #967 
I think the source of the flakiness here was we'd enter into this:
https://github.com/open-telemetry/otel-arrow/blob/b4bb1d87434528b7ffedc6aa5c76b512f6358182/rust/otap-dataflow/crates/engine/src/message.rs#L221-L241
And depending on how long it took between when the test setup function run, and when we invoked the validation function, we'd either hit the deadline or the pdata first. If we hit the deadline first, no writes are queued and the parquet exporter shuts down successfuly. This is not what we're trying to test  here.
To get around this, the test is now rewritten to manually drive the control messages, and have the parquet exporter receiving them at the same time. This way, we can have a better guarantee that there will be unflushed writes queued when it receives the …
=> Restore parquet exporter shutdown test and fix flakey implementation

rust/otel-arrow-rust/src/otap.rs, rust/otel-arrow-rust/src/otap/transform/transport_optimize.rs
Fixes: #952 
When we remove the transport encoding from an OTAP Batch (e.g. removing delta encoding ID columns so they're plain encoded), we were missing the resource/scope ID columns embedded within these struct arrays on the root record. This fixes the bug.
=> fix resource and scope IDs not getting decoded when removing transport encoding

rust/experimental/query_engine/engine-recordset/src/engine.rs, rust/experimental/query_engine/engine-recordset/src/scalars/parse_scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/summary/summary_data_expression.rs, rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/expressions/src/pipeline_expression.rs, rust/experimental/query_engine/expressions/src/scalars/convert_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/math_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/parse_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/temporal_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/text_scalar_expression.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_mathematical_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Simplify the signature for static resolution methods (less lifetimes)
* Implement some static folding when static resolution is manually invoked by parsers
=> [query-engine] Static resolution improvements

rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs, rust/experimental/query_engine/engine-recordset/src/primitives/value_storage.rs, rust/experimental/query_engine/engine-recordset/src/scalars/collection_scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/scalars/mod.rs, rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/scalars/text_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/primitives/array_value.rs, rust/experimental/query_engine/expressions/src/scalars/collection_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/mod.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/array_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/map_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/text_scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/lib.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_array_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Adds array concat, string concat, and string join expressions + recordset implementation
* Adds KQL support for `strcat`, `strcat_delim`, & `array_concat`
=> [query-engine] Concat & Join expressions

rust/experimental/query_engine/kql-parser/src/aggregate_expressions.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_array_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_conditional_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_conversion_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_mathematical_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_temporal_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/shared_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
Following up on feedback from @drewrelmas
=> [query-engine] Rename state -> scope in KQL parser code

rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_array_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs
=> [query-engine] Refactor try_resolve_value_type calls in KQL parser to use new helper method

.github/workflows/prepare-release.yml, .github/workflows/push-release.yml, .github/workflows/scripts/extract-changelog.sh
When using the `Prepare Release` and `Push Release` actions the extracted Changelog content displays incorrectly. The repo lint enforces line length in markdown files, leading to extra newlines in raw content:
```md
- Upgrade to v0.133.0 / v1.37.0 of collector dependencies.
[#890](https://github.com/open-telemetry/otel-arrow/pull/890),
[#1010](https://github.com/open-telemetry/otel-arrow/pull/1010)
- Notable upgrade, this also bumps minimum Go version from `1.23.0` to `1.24`,
see [collector
#13627](https://github.com/open-telemetry/opentelemetry-collector/pull/13627)
and [collector-contrib
#41968](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41968).
```
When viewing the [Changelog itself](https://github.com/open-telemetry/otel-arrow/blob/main/CHANGELOG.md) GitHub …
=> Script around Github markdown wrapping display differences for Release process

rust/otap-dataflow/Cargo.toml, rust/otap-dataflow/crates/otap/Cargo.toml, rust/otap-dataflow/crates/otap/src/parquet_exporter.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/error.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/idgen.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/schema.rs, rust/otel-arrow-rust/src/schema.rs
part of #863 
Because some OTAP fields are optional, in a stream of record batches we may receive subsequent batches with different schemas. Parquet doesn't support having row groups with different sets of column chunks, which means we need to know the schema a-priori when the writer is created.
This PR adds code to normalize the schema of the record batch before writing by:
- putting all the fields in the same order
- creating all null/default value columns for any missing column
The missing columns should have a small overhead when written to disk, because parquet will either write an entirely empty column chunk for the null column (all null count, no data), or and for all default-value columns, parquet will use dictionary and RLE encoding by default, leading to a small column chunk …
=> Parquet exporter handle optional fields

rust/otel-arrow-rust/src/otap/groups.rs
part of #1027 
- fix out of bounds slice access when splitting child if child does not contain parent IDs in the final split of the parent batch
- stop creating empty record batches for child splits if the child has no parent IDs in the range of the parent split
- `take` child batch from the input arrays so we don't fail the assertion in `generic_split` that there's nothing left in the input `batches`
=> [otel-arrow-rust] fix a few bugs splitting traces/logs when creating resized OTAP batches

rust/otap-dataflow/crates/engine/src/effect_handler.rs
- Avoid the string allocation by `format!` by directly writing the message and new line character to the buffer
=> [otap-df-enfine] Avoid allocation in info method

rust/experimental/query_engine/engine-recordset/src/engine.rs, rust/experimental/query_engine/engine-recordset/src/transform/transform_expressions.rs, rust/experimental/query_engine/engine-recordset/src/value_expressions.rs, rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/expressions/src/value_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/shared_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Removes `ImmutableValueExpression` in favor of just using `ScalarExpression` directly
I thought there might be other source of data but the way things worked out `ImmutableValueExpression` is really just some extra ceremony wrapping `ScalarExpression`.
=> [query-engine] Remove ImmutableValueExpression

rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs, rust/experimental/query_engine/parser-abstractions/src/parser_state.rs
* Moves folded/copied constant under `StaticScalarExpression`
Working towards automatically replacing expressions which are statically known with constant values. The way constants were defined previously we could have static values under `ScalarExpression:Static` or under `ScalarExpression::Constant(ConstantScalarExpression::Copy)`. For that to work resolution logic needs to handle\understand the special constant location everywhere which was proving to be very complex to build and likely difficult to maintain. To avoid all that complexity completely what this PR does is move folded/copied constants under the static tree so they are handled as any other static value.
=> [query-engine] Constant folding tweaks

rust/otap-dataflow/configs/fake-parquet.yaml, rust/otap-dataflow/configs/fake-perf.yaml, rust/otap-dataflow/crates/otap/src/parquet_exporter.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/config.rs, rust/otap-dataflow/crates/otap/src/parquet_exporter/idgen.rs
Fixes a few small issues with parquet exporter:
- fix `flush_when_older_than` missing value not being deserialized as `None` by serde
- fix bug generating unique IDs for ID columns with null values
Also adds a configuration example for generating parquet data.
=> Small parquet exporter fixes and add example config

go/pkg/record_message/arrow_record.go
I'm playing with otel arrow and noticed this orphaned `record.Schema()` call in NewLogsMessage. This PR removes the call.
=> fix: remove orphan record.Schema() call in NewLogsMessage

rust/otel-arrow-rust/src/otap/groups.rs, rust/otel-arrow-rust/src/otap/transform.rs, rust/otel-arrow-rust/src/otap/transform/transport_optimize.rs
Closes: #1026 
Improve batching performance by using the arrow row format for multicolumn sort where possible.
We do this by creating a reusable function called `otap::transform::sort_to_indices` and using this both in the batching code and in the transport optimization encoding code (which is where this was refactored from).
=> Use Arrow row format when sorting for batching if possible

rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/pipeline_expression.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/kql-parser/src/logical_expressions.rs, rust/experimental/query_engine/kql-parser/src/query_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Support accessors into constant values
This enables a bunch of things but the main one IMO is efficient value lookup:
```
let lookup =  parse_json('[\"Failure\", \"Success\"]');
source | extend Status = coalesce(lookup[NumericStatus], 'Unknown')
```
=> [query-engine] Support accessors into constant values

rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs, rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/engine-recordset/src/scalars/text_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/logical_expressions.rs, rust/experimental/query_engine/expressions/src/primitives/value.rs, rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs, rust/experimental/query_engine/expressions/src/scalars/text_scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs
* Adds expression and recordset engine implementation for simple regex capture (single group, first match)
* Adds KQL parsing for `extract` using the new expression
=> [query-engine] Regex capture support

rust/otap-dataflow/Cargo.toml, rust/otap-dataflow/crates/otap/Cargo.toml, rust/otap-dataflow/crates/otap/src/otap_grpc.rs, rust/otap-dataflow/crates/otap/src/otap_grpc/middleware.rs, rust/otap-dataflow/crates/otap/src/otap_grpc/middleware/zstd_header.rs, rust/otap-dataflow/crates/otap/src/otap_receiver.rs
=> Add tonic middleware to handle go exporter's grpc-encoding zstdarrow header value

rust/otap-dataflow/crates/config/src/engine.rs, rust/otap-dataflow/crates/config/src/node.rs, rust/otap-dataflow/crates/config/src/pipeline.rs, rust/otap-dataflow/crates/config/src/pipeline_group.rs, rust/otap-dataflow/crates/otap/src/compression.rs, rust/otap-dataflow/crates/otap/src/debug_processor/config.rs, rust/otap-dataflow/crates/otap/src/fake_data_generator/config.rs, rust/otap-dataflow/crates/otap/src/otap_exporter.rs, rust/otap-dataflow/crates/otap/src/otap_exporter/config.rs, rust/otap-dataflow/crates/otap/src/otap_receiver.rs, rust/otap-dataflow/crates/otap/src/otlp_exporter.rs, rust/otap-dataflow/crates/otap/src/otlp_receiver.rs, rust/otap-dataflow/crates/otap/src/perf_exporter/config.rs, rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs, rust/otap-dataflow/crates/state/src/config.rs, rust/otap-dataflow/crates/telemetry/src/config.rs
- Add #[serde(deny_unknown_fields)] to user-facing config structs:
- EngineConfig/EngineSettings/TelemetrySettings/HttpAdminSettings
- PipelineConfig/PipelineSettings
- PipelineGroupConfig/Quota
- NodeUserConfig/HyperEdgeConfig
- telemetry::Config, state::Config
- otap: exporter/receiver/debug/fake_data/syslog_cef/perf configs
- Normalize enums to canonical snake_case where applicable:
- otap::CompressionMethod
- otap::otap_exporter::ArrowPayloadCompression
- syslog_cef::Protocol
- Update existing tests to use canonical values (e.g., gzip), and add unit tests to assert unknown fields are rejected and only snake_case enum variants are accepted.
This implements PR 1 of #1099: strict parsing and canonical option casing.
=> [otap-dataflow] Config: enforce serde strictness and normalize option casing

rust/otap-dataflow/crates/pdata-views/src/views/metrics.rs, rust/otap-dataflow/crates/telemetry/src/instrument.rs, rust/otel-arrow-rust/src/otap.rs, rust/otel-arrow-rust/src/otap/groups.rs, rust/otel-arrow-rust/src/pdata/otlp/mod.rs
- Mark methods `const` where applicable
- Simplify the handling of `ArrowPayloadType::MultivariateMetrics` logic within the `match` statement to avoid recursive calling of the method `child_payload_types`
=> Minor refactoring

rust/otap-dataflow/crates/otap/src/encoder.rs, rust/otap-dataflow/crates/otap/src/encoder/cbor.rs, rust/otel-arrow-rust/src/otlp/attributes.rs, rust/otel-arrow-rust/src/otlp/attributes/cbor.rs, rust/otel-arrow-rust/src/otlp/common.rs, rust/otel-arrow-rust/src/otlp/logs.rs, rust/otel-arrow-rust/src/validation/scenarios.rs
closes: #1121 
Stop going to the intermediate prost struct when decoding Map / Slice AnyValues
=> Encode OTAP -> OTLP proto bytes directly for Slice/Map AnyValues

rust/otap-dataflow/crates/otap/src/otlp_exporter.rs
- Remove unnecessary conversion to `OtlpProtoBytes`
=> [otap-df-otap] Simplify OTLP Exporter

rust/otap-dataflow/crates/otap/src/attributes_processor.rs, rust/otel-arrow-rust/src/otap/transform.rs
- The transforms for `AttributesProcessor` are not changed after initialization
- Currently we are `AttributesTransform::validate()` in the hot-path. This method allocates a `BTreeSet` when called
- In this PR, I have updated the code to perform validation of `AttributesTransform` just one in the `new` method
=> [perf][otap-df-otap] Avoid redundant allocations for validating AttributeTransform config

rust/otap-dataflow/crates/otap/src/attributes_processor.rs, rust/otel-arrow-rust/benches/attribute_transform.rs, rust/otel-arrow-rust/src/otap/transform.rs
- Reference the precomputed bytes representation of the transforms instead of collecting them into `vec`s repeatedly
- Updated the transform benchmarks to use `black_box` around the input and to make the measurement more targeted
=> [perf] Avoid allocations in transform plan creation hot-path

rust/experimental/query_engine/expressions/src/pipeline_expression.rs, rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs, rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs, rust/experimental/query_engine/expressions/src/transform_expressions.rs, rust/experimental/query_engine/expressions/src/value_accessor.rs, rust/experimental/query_engine/expressions/src/value_expressions.rs
Relates to #1178
* Implements `fmt_with_indent` for more expressions. Note: I had CoPilot do the initial work but I tweaked and cleaned everything up manually.
Examples:
```
Pipeline
├── Query: ""
├── Constants: []
├── Initializations: []
└── Expressions:
└── Remove
└── Target(Mutable): Variable
├── Name: "var"
└── Accessor:
└── String: "field"
```
```
Pipeline
├── Query: ""
├── Constants: []
├── Initializations: []
└── Expressions:
└── RemoveMapKeys(Retain)
├── Target(Mutable): Source
│                    └── Accessor:
│                        └── String: "Attributes"
├── Keys[0](Scalar): Variable
│                    ├── Name: "var1"
│                    └── Accessor: None
└── Keys[1](Scalar): Variable
├── Name: "var2"
└── Accessor: None
```
```
Pipeline
├── Query: "\nsource\n | …
```
=> [query-engine] Implement fmt_with_indent for more expressions

rust/otel-arrow-rust/src/otap/transform.rs
- In the current implementation, we always allocate a `vec` when merging transform ranges (even if there is no merge required for example if there are either only replacement ranges or only delete ranges)
- With this PR, we append the `KeyTransformRangeType` data from the get-go and store them in `KeyReplacementPlan` and `KeyDeletePlan`. This allows us to simply refer to these fully self-contained ranges in the `merge_transform_ranges` method if there is no merge required.
=> [perf] Avoid unnecessary vec allocation for merged transforms

rust/experimental/query_engine/expressions/src/scalars/parse_scalar_expression.rs
Relates to #1178
Example:
```
Pipeline
├── Query: "\nsource\n | extend\n    c1 = parse_json(json_attr),\n    c2 = parse_regex(regex_attr),\n    c3 = parse_regex(regex_attr, regex_options_attr)\n "
├── Constants: []
├── Initializations: []
└── Expressions:
├── Set
│   ├── Source(Scalar): ParseJson(Scalar): Source
│   │                                      └── Accessor:
│   │                                          ├── String: "Attributes"
│   │                                          └── String: "json_attr"
│   └── Destination(Mutable): Source
│                             └── Accessor:
│                                 ├── String: "Attributes"
│                                 └── String: "c1"
├── Set
│   ├── Source(Scalar): ParseRegex
│   │                   ├── Pattern(Scalar): Source …
```
=> [query-engine] Implement fmt_with_indent for ParseScalarExpression

rust/experimental/query_engine/kql-parser/src/kql.pest, rust/experimental/query_engine/kql-parser/src/lib.rs, rust/experimental/query_engine/kql-parser/src/scalar_array_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_conditional_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_conversion_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_expression.rs, rust/experimental/query_engine/kql-parser/src/scalar_logical_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_mathematical_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_parse_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs, rust/experimental/query_engine/kql-parser/src/scalar_temporal_function_expressions.rs
Noticed we have the `LogicalExpression` support for `not()` (used in conjunction with `where`) but never added this standalone in the KQL grammar
=> Add support for KQL not()

rust/otap-dataflow/crates/otap/src/syslog_cef_receiver/parser/parsed_message.rs, rust/otap-dataflow/crates/otap/src/syslog_cef_receiver/parser/rfc5424.rs
- Add support for BOM detection to comply with RFC 5424: https://www.rfc-editor.org/rfc/rfc5424
=> [otap-df-otap] Add support for BOM detection for Syslog parser for RFC 5424

tools/pipeline_perf_test/test_suites/integration/templates/configs/engine/otap-attr-otap.yaml, tools/pipeline_perf_test/test_suites/integration/templates/configs/engine/otlp-attr-otap.yaml, tools/pipeline_perf_test/test_suites/integration/templates/configs/engine/syslog-attr-otap.yaml, tools/pipeline_perf_test/test_suites/integration/templates/configs/loadgen/config.yaml.j2
Until the Arrow-rs patch mentioned in https://github.com/open-telemetry/otel-arrow/issues/1129 is merged and in-use here, we need to disable the payload compression in the perf test benchmarks.
=> [PerfTest] temporarily remove arrow payload compression in benchmark suites

rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs, rust/experimental/query_engine/kql-parser/src/tabular_expressions.rs
* Improve the schema validation in KQL accessor expressions when `source` is referenced directly
We have schema validation in the KQL parser. When schema is defined we'll use it to resolve types and detect invalid usage when possible.
Currently we only do schema validation when `source` is referenced implicitly. For example `extend c = SomeField`. What this PR does is extend that validation to also run when `source` is referenced explicitly for example `extend c = source.SomeField`.
=> [query-engine] Improve validation in KQL accessor expressions when source is referenced directly

rust/otap-dataflow/crates/otap/src/otap_exporter.rs
- Use the argument `signal_type` instead of hardcoded `SignalType::Logs`
=> [otap-df-otap] Fix signal type input in OTAP Exporter

rust/otel-arrow-rust/src/otap/schema.rs
- Use `sort_unstable_by_key` instead of `sort_by` for higher efficiency
- Optimize iterator usage by using `extend` with a `Range` instead of `enumerate` and repeated `push` operations
- Truncate `sort_buf` when writing `Union` types
- Fix unit test
=> [otel-arrow-rust] Micro optimizations and minor fixes to SchemaBuilder

rust/otap-dataflow/crates/otap/src/otlp_exporter.rs
Closes: https://github.com/open-telemetry/otel-arrow/issues/1231
Try to fix test failure observed here: 
https://github.com/open-telemetry/otel-arrow/actions/runs/18234929441/job/51926734884
The issue here was that, when we were asserting that the "logs_failed" metric was incremented after we send a request which could not be serviced, we'd send the pdata, then send the `CollectTelemetry` pdata message, then wait to receive telemetry on the metrics reporter channel. The problem with this is that the channel that gets fed into the exporter biases control messages, so in some cases the exporter would see the `CollectTelemetry` message first. When this happens, there could be no telemetry to report, which means nothing would be sent on the pdata reporter channel and the test would deadlock. …
=> fix otlp exporter test flake

rust/otap-dataflow/crates/otap/src/otap_exporter.rs
closes #1096 
Fixes issue where the `start` method of the exporter would exit with error immediately if the server identified by config.grpc_endpoint is not ready
=> handle server not ready when starting OTAP Exporter
