open-telemetry/otel-arrow

collector/receiver/otelarrowreceiver/internal/arrow/arrow_test.go

After merging https://github.com/open-telemetry/otel-arrow/pull/24, unit tests for otelarrowreceiver were failing and I did not catch that. This PR fixes the unit tests by adding in support for an extra call to Send() the receiver will do (with arrowpb.StatusCode_STREAM_SHUTDOWN), to signal shutdown to the client.
Addresses https://github.com/open-telemetry/otel-arrow/pull/29#issuecomment-1701399304

Fix otelarrowreceiver unit tests

---

collector/exporter/otelarrowexporter/dead.code

File was accidentally added in #40.

Remove accidental file

---

CONTRIBUTING.md
README.md

Modifies the README to reflect Beta status.
Replaces a lot of text to reflect this new level of maturity.

Update README for beta status

---

collector/receiver/otelarrowreceiver/config.go
collector/receiver/otelarrowreceiver/config_test.go
collector/receiver/otelarrowreceiver/testdata/config.yaml

Add a memory limit mapstructure tag

---

CODEOWNERS

@codeboten has been offering help and is an Otel Collector maintainer. :-)

Add Alex Boten as otel-arrow approver

---

CHANGELOG.md
RELEASING.md

Add a changelog describing releases v0.1.0 through v0.6.0

---

collector/processor/concurrentbatchprocessor/batch_processor.go
collector/processor/concurrentbatchprocessor/metrics.go

The new metric improves our ability to understand whether the max-inflight-bytes is set correctly.
TODO: Document the component batch processor, including its metrics. Depends on #94 and when/how we try to push this code upstream.
Part of #110.

Add latency metric for batch export

---

CHANGELOG.md
collector/exporter/otelarrowexporter/internal/arrow/bestofn.go
collector/exporter/otelarrowexporter/internal/arrow/exporter.go
collector/exporter/otelarrowexporter/internal/arrow/prioritizer.go
collector/exporter/otelarrowexporter/internal/arrow/stream.go
collector/exporter/otelarrowexporter/internal/arrow/stream_test.go
collector/exporter/otelarrowexporter/otelarrow_test.go
collector/receiver/otelarrowreceiver/internal/arrow/arrow.go

Apply jitter once per lifetime, not once per stream

---

Makefile
pkg/otel/common/arrow/allocator.go
versions.yaml

Fix two non-breaking problems discovered in the updated release process as of v0.24.0.

Remove more makefile, add missing line in versions

---

CHANGELOG.md
collector/cmd/otelarrowcol/go.mod
collector/cmd/otelarrowcol/main.go
collector/otelarrowcol-build.yaml
versions.yaml

Release 0.28

---

CHANGELOG.md
collector/cmd/otelarrowcol/go.mod
collector/cmd/otelarrowcol/main.go
collector/otelarrowcol-build.yaml
versions.yaml

Update OTel-Collector dependencies to v0.113.0.

Release v0.30.0

---

CHANGELOG.md
Makefile
collector/cmd/otelarrowcol/components.go
collector/cmd/otelarrowcol/go.mod
collector/cmd/otelarrowcol/main.go
collector/otelarrowcol-build.yaml

Finishes the work done in #277.

Use the v0.117.0 builder, update otelarrowcol build to 117

---

.github/workflows/ci.yml

Regarding issue #289 
Add CodeQL to the Go CI following usage in [Collector-Contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/codeql-analysis.yml)

Add CodeQL analysis to CI

---

CODEOWNERS

Copying #328 so @jmacd can approve and merge

Update codeowners to use proper group

---

.github/renovate.json5

Similar to https://github.com/open-telemetry/community/pull/2662/files and https://github.com/open-telemetry/sig-security/pull/97 ...
This should take care of proper pinned dependencies etc.

chore: Add renovate

---

CONTRIBUTING.md
README.md

Part of #428. Give thanks to @moh-osman3 and @codeboten as we add new approvers.

Update current team in CONTRIBUTING.md

---

rust/otel-arrow-rust/.clippy.toml
rust/otel-arrow-rust/Cargo.toml
rust/otel-arrow-rust/build.rs
rust/otel-arrow-rust/src/arrays.rs
rust/otel-arrow-rust/src/decode/decoder.rs
rust/otel-arrow-rust/src/lib.rs
rust/otel-arrow-rust/src/otlp/attributes/store.rs
rust/otel-arrow-rust/src/otlp/logs.rs
rust/otel-arrow-rust/src/otlp/metrics.rs
rust/otel-arrow-rust/src/otlp/metrics/data_points/histogram.rs
rust/otel-arrow-rust/src/otlp/metrics/data_points/summary.rs
rust/otel-arrow-rust/src/otlp/metrics/exemplar.rs
rust/otel-arrow-rust/src/pdata/mod.rs
rust/otel-arrow-rust/src/pdata/otlp/tests.rs
rust/otel-arrow-rust/src/proto/mod.rs
rust/otel-arrow-rust/src/validation/collector.rs
rust/otel-arrow-rust/src/validation/otap.rs
rust/otel-arrow-rust/src/validation/scenarios.rs
rust/otel-arrow-rust/src/validation/service_type.rs
rust/otel-arrow-rust/src/validation/tcp_stream.rs
rust/otel-arrow-rust/src/validation/testdata.rs

Fixes: https://github.com/open-telemetry/otel-arrow/issues/423

fix clippy & rust linter config and issues in otel-arrow-rust

---

tools/pipeline_perf_test/orchestrator/orchestrator.py

This PR adds basic cpu / memory utilization monitoring and reporting for containers under test running via docker and k8s.
Follow up PRs will refactor to docker/k8s api client libraries, implement better solution for k8s based containers, and improve flow for ensuring monitored periods are more tightly controlled.

Perf - add resource monitoring for docker / k8s containers under test

---

rust/otel-arrow-rust/README.md

Updates the README.md file in otel-arrow-rust to relfect the current progress on the encoding / decoding work

docs: update otel-arrow-rust README with encoding/decoding progress

---

rust/experimental/query_engine/kql-parser/src/kql_parser.rs

* Clean up clippy warnings from #551

[query-engine] KQL bool, double, & real - linting

---

rust/experimental/query_engine/Cargo.toml
rust/experimental/query_engine/expressions/Cargo.toml
rust/experimental/query_engine/expressions/src/scalar_expressions.rs
rust/experimental/query_engine/kql-parser/Cargo.toml
rust/experimental/query_engine/kql-parser/src/date_utils.rs
rust/experimental/query_engine/kql-parser/src/kql.pest
rust/experimental/query_engine/kql-parser/src/kql_parser.rs
rust/experimental/query_engine/kql-parser/src/lib.rs

* Adds parsing of KQL datetime expression

[query-engine] KQL datetime

---

rust/experimental/query_engine/engine-recordset/src/expression.rs
rust/experimental/query_engine/engine-recordset/src/value_path.rs

* Add expression and valuepath to recordset engine

[query-engine] Add expression and valuepath to recordset engine

---

rust/experimental/query_engine/engine-recordset/src/error.rs
rust/experimental/query_engine/engine-recordset/src/execution_context.rs
rust/experimental/query_engine/engine-recordset/src/macros.rs
rust/experimental/query_engine/engine-recordset/src/pipeline_expression.rs
rust/experimental/query_engine/engine-recordset/src/summary.rs

* Adds ExecutionContext, Error, Summary, PipelineExpression and helper macros to the recordset engine implementation

[query-engine] Add execution context & pipeline expression to recordset engine

---

rust/experimental/query_engine/expressions/src/lib.rs
rust/experimental/query_engine/expressions/src/logical_expressions.rs
rust/experimental/query_engine/expressions/src/scalar_expressions.rs
rust/experimental/query_engine/kql-parser/src/kql.pest
rust/experimental/query_engine/kql-parser/src/kql_parser.rs

* Adds support for parsing KQL logical expressions into query engine expressions

[query-engine] Add support for parsing KQL logical expressions

---

rust/experimental/query_engine/expressions/src/lib.rs
rust/experimental/query_engine/expressions/src/scalar_expressions.rs
rust/experimental/query_engine/expressions/src/static_scalar_expressions.rs
rust/experimental/query_engine/kql-parser/src/kql_parser.rs

* Refactor static scalar expressions into their own enum

[query-engine] Static scalar expressions

---

rust/experimental/query_engine/engine-recordset/src/data/data_record.rs
rust/experimental/query_engine/engine-recordset/src/data/data_record_batch.rs
rust/experimental/query_engine/engine-recordset/src/data/data_record_resolver.rs
rust/experimental/query_engine/engine-recordset/src/data/data_record_resolver_cache.rs
rust/experimental/query_engine/engine-recordset/src/data/mod.rs

* Defines data record and data record batch in the recordset query engine

[query-engine] Add data record and batch definitions to recordset engine

---

rust/otap-dataflow/crates/engine/src/effect_handler.rs

- Add UDP support for local receiver

[otel-arrow-rust] Add UDP support

---

rust/experimental/query_engine/expressions/src/transform_expressions.rs
rust/experimental/query_engine/kql-parser/src/kql_parser.rs

* KQL `project-keep` parsing will now decide to use `RemoveMapKeys` over `ReduceMap` if the query is only referencing statically known top-level keys

[query-engine] Optimize KQL project-keep parsing

---

rust/experimental/query_engine/kql-parser/src/kql_parser.rs

* KQL `project` parsing will now decide to use `RemoveMapKeys` over `ReduceMap` if the query is only referencing statically known top-level keys

[query-engine] Optimize KQL project parsing

---

.github/workflows/pipeline-perf-test.yml

Trying new runner, on the host itself. If this does not work, then will try to run container.

PipelinePerfTest - try to use new runner

---

rust/experimental/query_engine/parser-abstractions/src/parser_state.rs

* Add a spot for constants on `ParserState`

[query-engine] Support constants on ParserState

---

rust/experimental/query_engine/expressions/src/pipeline_expression.rs

[query-engine] Add missing getter on PipelineExpression

---

rust/experimental/query_engine/expressions/src/primitives/value.rs
rust/experimental/query_engine/expressions/src/primitives/value_type.rs
rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs

* Introduce Null type into expressions

[query-engine] Introduce null type in expressions

---

rust/experimental/query_engine/expressions/Cargo.toml
rust/experimental/query_engine/expressions/src/primitives/array_value.rs
rust/experimental/query_engine/expressions/src/primitives/map_value.rs
rust/experimental/query_engine/expressions/src/primitives/value.rs

* Implement to_string for map and array values

[query-engine] Implement to_string for map and array values

---

rust/experimental/query_engine/expressions/src/primitives/value.rs

* Implement map and array equality rules when compared to a string

[query-engine] Implement array and map string equality

---

rust/experimental/query_engine/expressions/src/primitives/array_value.rs
rust/experimental/query_engine/expressions/src/primitives/map_value.rs
rust/experimental/query_engine/expressions/src/primitives/value.rs
rust/experimental/query_engine/expressions/src/scalars/statics/array_scalar_expression.rs
rust/experimental/query_engine/expressions/src/scalars/statics/map_scalar_expression.rs
rust/experimental/query_engine/expressions/src/scalars/statics/resolved_static_scalar_expression.rs
rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs
rust/experimental/query_engine/expressions/src/transform_expressions.rs

* Add 'AsValue' trait in expressions
* Implement `Display` for `Value` and remove custom to_string implementation

[query-engine] Introduce AsValue and implement Display for to_string

---

.github/renovate.json5

#731 and #732 should have been combined, small oversight in Renovate rules

Combine .yml and .yaml Renovate updates

---

rust/experimental/query_engine/engine-recordset2/src/engine.rs
rust/experimental/query_engine/engine-recordset2/src/execution_context.rs
rust/experimental/query_engine/engine-recordset2/src/lib.rs
rust/experimental/query_engine/engine-recordset2/src/log_message.rs
rust/experimental/query_engine/engine-recordset2/src/logical_expressions.rs
rust/experimental/query_engine/engine-recordset2/src/transform/mod.rs
rust/experimental/query_engine/engine-recordset2/src/transform/transform_expressions.rs

Relates to #747
* Adds entry point and context code for the new recordset engine

[query-engine] Add entry point and context to new recordset engine

---

rust/experimental/query_engine/engine-recordset2/src/execution_context.rs
rust/experimental/query_engine/engine-recordset2/src/lib.rs
rust/experimental/query_engine/engine-recordset2/src/primitives/mod.rs
rust/experimental/query_engine/engine-recordset2/src/primitives/resolved_value_mut.rs
rust/experimental/query_engine/engine-recordset2/src/value_expressions.rs

Relates to #747
* Adds value expressions to recordset2 engine

[query-engine] Add value expressions to recordset2 engine

---

tools/pipeline_perf_test/backend/requirements.txt
tools/pipeline_perf_test/load_generator/requirements.txt
tools/pipeline_perf_test/orchestrator/requirements.txt

Fixes #760 
- replace all requirements.txt >= statements with == to help renovate understand them
- Updated packages to the version installed with a fresh 'pip install' in the >= setup.

[PerfTest] Pin python requirements to exact version

---

rust/experimental/query_engine/engine-recordset2/src/transform/mod.rs
rust/experimental/query_engine/engine-recordset2/src/transform/reduce_map_transform_expression.rs
rust/experimental/query_engine/engine-recordset2/src/transform/transform_expressions.rs

Relates to #747
* Adds ReduceMap transform expression implementation in recordset2 engine

[query-engine] Add ReduceMap transform to recordset2 engine

---

rust/experimental/query_engine/kql-parser/src/kql.pest
rust/experimental/query_engine/kql-parser/src/scalar_expression.rs

addressing KQL null_literal on issue #722

Add null_literal support for KQL query_engine

---

.github/workflows/prepare-release.yml
.github/workflows/scripts/create-release-branch.sh
CHANGELOG.md
collector/otelarrowcol-build.yaml

Noticed missing thing in `prepare-release` for `v0.40.0`

Update prepare-release to increment otelarrowcol-build.yaml version

---

rust/experimental/query_engine/engine-recordset2/src/engine.rs
rust/experimental/query_engine/engine-recordset2/src/primitives/value_storage.rs

* Adds APIs for accessing the raw values behind value storage
* Adds an API for borrowing the record when working with results

[query-engine] Recordset2 engine API tweaks

---

rust/otap-dataflow/crates/otap/src/perf_exporter/exporter.rs

Update the perf exporter to use async write instead of the std write calls which are blocking

[otap-dataflow] fix blocking calls from perf-exporter

---

rust/experimental/query_engine/kql-parser/src/query_expression.rs

* In KQL parser if there is a Pest failure return a more friendly message

[query-engine] Improve error messages in KQL parser when Pest can't parse a query

---

rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs
rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs
rust/experimental/query_engine/engine-recordset/src/transform/reduce_map_transform_expression.rs
rust/experimental/query_engine/engine-recordset/src/transform/transform_expressions.rs
rust/experimental/query_engine/engine-recordset/src/value_expressions.rs

* Fixes borrow errors when the engine tries to write to something using a value it read from the same thing

[query-engine] Fix borrow errors in recordset engine

---

rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/common.rs
rust/experimental/query_engine/engine-recordset/src/primitives/value_storage.rs
rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs
rust/experimental/query_engine/expressions/src/primitives/array_value.rs
rust/experimental/query_engine/expressions/src/scalars/statics/array_scalar_expression.rs

* Adds range support in array selection
* Fix some merge issues from case + static value refactor PRs

[query-engine] Support selecting array items using range

---

rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs
rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs
rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs

Relates to #722 (slice will be used for substring KQL)
* Implements slice expression

[query-engine] Implement slice expression

---

rust/experimental/query_engine/kql-parser/src/kql.pest
rust/experimental/query_engine/kql-parser/src/scalar_conversion_function_expressions.rs
rust/experimental/query_engine/kql-parser/src/scalar_expression.rs

Add KQL implementation for rest of to* convert functions

---

rust/experimental/query_engine/Cargo.toml
rust/experimental/query_engine/engine-recordset/Cargo.toml
rust/experimental/query_engine/engine-recordset/src/primitives/owned_value.rs
rust/experimental/query_engine/engine-recordset/src/scalar_expressions.rs
rust/experimental/query_engine/expressions/Cargo.toml
rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs
rust/experimental/query_engine/expressions/src/scalars/statics/static_scalar_expressions.rs

Relates to #722
* Adds ParseJson scalar in expressions and implementation in recordset engine

[query-engine] ParseJson scalar

---

rust/experimental/query_engine/engine-recordset/src/scalars/math_scalar_expressions.rs
rust/experimental/query_engine/expressions/src/primitives/value.rs
rust/experimental/query_engine/expressions/src/scalars/convert_scalar_expression.rs
rust/experimental/query_engine/expressions/src/scalars/math_scalar_expression.rs

Relates to #722 
* Adds expressions and implementation in recordset for `+` `-` `*` and `/`

[query-engine] More math: + - * /

---

rust/experimental/query_engine/engine-recordset/src/scalars/scalar_expressions.rs
rust/experimental/query_engine/engine-recordset/src/scalars/text_scalar_expressions.rs

* Adds a few missing warning diagnostics for invalid input conditions

[query-engine] Diagnostic improvements

---

rust/otap-dataflow/crates/controller/src/lib.rs
rust/otap-dataflow/crates/engine/src/runtime_pipeline.rs

- Update the result type of `run_pipeline_thread` and `run_forever` method

[otap-controller] Update Result Type

---

rust/otap-dataflow/crates/engine/src/pipeline_ctrl.rs

- Use only one HashMap to track the timer state instead of three different ones
- Instead of 3-4 HashMap lookups per operation we now only have one lookup
- This also offers better cache locality

[otap-df-engine] Simplify timer control

---

rust/experimental/query_engine/engine-recordset/src/logical_expressions.rs
rust/experimental/query_engine/expressions/src/logical_expressions.rs
rust/experimental/query_engine/expressions/src/primitives/value.rs

* Adds an expression and implementation for performing regex string match evaluation

[query-engine] Add matches logical expression and implementation

---

rust/otap-dataflow/crates/controller/src/lib.rs
rust/otap-dataflow/crates/otlp/Cargo.toml
rust/otap-dataflow/crates/otlp/src/otlp_batch_processor.rs

[otap-dataflow] [otlp]: validate batch_processor config and register processor factory

---

rust/otap-dataflow/crates/otap/src/otap_receiver.rs
rust/otap-dataflow/crates/otap/src/otlp_receiver.rs

By design, `tokio::select` returns whenever any branch completes and cancels the remaining branches.  We have placed `tokio::select!` within a `loop` and it has two branches: one for processing control messages and one for serving requests. The control message branch would complete anytime we finish processing any control message (for example, receiving shutdown, reporting telemetry, etc.).  The other branch for serving requests would usually not complete until something goes wrong with the `TcpListenerStream` itself - it's meant to run indefinitely.
This means that anytime we report telemetry (or process any other control message) we would return from `tokio::select!` and start the loop again. That leads to:
- Repeated creation of server and related service instances on every control …

[otap-df-otap] Fix OTLP and OTAP receivers

---

rust/otap-dataflow/crates/otap/Cargo.toml
rust/otap-dataflow/crates/otap/src/lib.rs
rust/otap-dataflow/crates/otap/src/otap_batch_processor.rs
rust/otap-dataflow/crates/otap/src/parquet_exporter/object_store.rs

Integration work for otap_batch_processor and otappdata batching capabilities

[otap-dataflow] otap pdata integration for otap_batch_processor

---

rust/otap-dataflow/crates/otap/src/syslog_cef_receiver.rs

Update the from_config method to use the config parameter

[otap-dataflow] syslog-cef-receiver update from_config method

---

rust/experimental/query_engine/kql-parser/src/kql.pest
rust/experimental/query_engine/kql-parser/src/lib.rs
rust/experimental/query_engine/kql-parser/src/scalar_expression.rs
rust/experimental/query_engine/kql-parser/src/scalar_parse_function_expressions.rs
rust/experimental/query_engine/kql-parser/src/scalar_primitive_expressions.rs
rust/experimental/query_engine/kql-parser/src/scalar_string_function_expressions.rs

* Adds regex parsing in KQL
* Cleans up the KQL pest a bit

[query-engine] KQL regex parsing and cleanup

---

rust/otap-dataflow/crates/otap/src/otap_exporter.rs

[otap-df-otap] Fix indentation

---

rust/experimental/query_engine/engine-recordset-otlp-bridge/Cargo.toml
rust/experimental/query_engine/engine-recordset-otlp-bridge/src/bridge.rs
rust/experimental/query_engine/engine-recordset-otlp-bridge/src/bridge_options.rs
rust/experimental/query_engine/engine-recordset-otlp-bridge/src/lib.rs
rust/experimental/query_engine/engine-recordset-otlp-bridge/src/proto/common.rs
rust/experimental/query_engine/engine-recordset-otlp-bridge/tests/otlp_kql_recordset.rs
rust/experimental/query_engine/engine-recordset/src/primitives/resolved_value.rs
rust/experimental/query_engine/expressions/src/primitives/array_value.rs
rust/experimental/query_engine/expressions/src/scalars/statics/array_scalar_expression.rs
rust/experimental/query_engine/parser-abstractions/src/parser.rs

[query-engine] Support passing attribute schema in OTLP bridge

---

rust/otap-dataflow/crates/otap/src/otap_exporter.rs
rust/otap-dataflow/crates/otap/src/otlp_exporter.rs

- Cancel telemetry timer on shutdown for OTAP and OTLP exporters

[otap-df-otap] Cancel telemetry timer on shutdown for OTAP and OTLP exporters

---

rust/otap-dataflow/crates/otap/src/attributes_processor.rs

- Introduce a convenient `const fn noop()` to check if there are any transforms to apply
- Make `attrs_payloads` and `apply_transform_with_stats` methods of `AttributeProcessor`. This provides better enapsulation removing the need to pass `&self.transform` and `&self.domains` as parameters

[otap-df-otap] Refactor AttributesProcessor

---

rust/experimental/query_engine/expressions/src/scalars/scalar_expressions.rs

I had intended for this to be part of #1178 but forgot to push. Sorry!

[query-engine] Update Conditional formatting when displayed

---

rust/otap-dataflow/crates/otap/src/otap_exporter.rs

- Minor refactoring in OTAP Exporter

[otap-df-otap] Minor refactoring in OTAP Exporter
